---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  path: ./kubernetes/main/apps/infrastructure/external-secrets
  prune: true
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
