authentik:
  secret_key: "${AUTHENTIK_KEY}"
  postgresql:
    password: "${AUTHENTIK_POSTGRES_PASSWORD}"
server:
  ingress:
    enabled: true
    annotations:
      external-dns.alpha.kubernetes.io/target: "auth.dnsk.xyz"
    ingressClassName: external
    hosts:
      - "auth.dnsk.xyz"
postgresql:
  enabled: true
  auth:
    password: "${AUTHENTIK_POSTGRES_PASSWORD}"
redis:
  enabled: true
