apiVersion: v1
kind: Secret
metadata:
  name: pihole-api-token
  namespace: network
stringData:
  api_token: ENC[AES256_GCM,data:caQ0bbY=,iv:5L1LnoECJA7yPNoLy/rSDEOpwn9DzoJYsfH8uCWjAZc=,tag:PVH6Uw6VjZmner5X/89czw==,type:str]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVRlV4RmJ3WmNRQldsWUl6
        VTJkT3phb0ZGSExQV0ZaWTc1RTZ0TENoc0VvCk9CQVNRc1lYK3h2M2F2MkRUWXVG
        VlZpZnQ4UVBBNWxlK3YzSlJBeFFxQ1kKLS0tIFFZQW1rTWIxUUVvZ1NIYlNyTDVo
        MURwNmxXaVJZV0ZVb2RqaUpTZEpIRUEKH6Iq6+azhNsHp7dhTw7uJC1KQZx7H+t7
        lQ1sIhJsZnqR6jwXVrta0KUT5juFvLNB80hGkQqQOSQufjcLsQK4gw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-31T08:10:48Z"
  mac: ENC[AES256_GCM,data:tqIsvmzdQSbnIV1mbKqN9EFFlOpnelmUAKA+KKYL2g3CoHuFUmY6VLOpWkVshEdNAyhFLa4/W6MOGDsSzLbfzoheBQwtrwmj5BavY0gROQe6MqkqW+OwssHD5kkKiR/8Iq1ifOG5tyB9xI1usp6uW46VulKrq78oGwNL/85YTGw=,iv:Tbh/Rl9oerUYfcKJCUG6KdocRR9hYUNiHQhOd+NHiRE=,tag:JgnOPYtNqZOzne0ksJWGoA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
