apiVersion: v1
kind: Secret
metadata:
  name: influxdb-admin-credentials
  namespace: goriva-si
type: Opaque
stringData:
  #ENC[AES256_GCM,data:cCsf4Rq9cDlmMTI1Xyd9sgKavPbcxTVZn+HV6ATHvg==,iv:86nZHcjYEFHrIlsWZdZAzIM3atnr1Mn5QsX4YcF90wk=,tag:a4D7gozKkVX6AA+mGmKUKg==,type:comment]
  admin-password: ENC[AES256_GCM,data:Ix5lqu9ysDX4Fiu8V7BPy2Ztcog=,iv:QUd9LDliK+7i0aUaE8WAEUSgKr8XEDEY/KzamhFxa3g=,tag:b4lGdgt3WFUip3aJ4u9fLg==,type:str]
  #ENC[AES256_GCM,data:C2wDpdXPysgttphMvDLGli/TaeDxuP35kU2ToF1M/qzZpawYhV5Vi3wL7eSJ,iv:U/b5bMzI1Jzkumb5BpLvk7u/2jTFHLPtfTvfbw9KJK8=,tag:zEsymEP4JyTOxiO11ryNnw==,type:comment]
  admin-token: ENC[AES256_GCM,data:Y1HbBS0Ly/QPcj/85dBi+AdAbvHaDF+DrBFyaRDP6o42wgh/BxpjD0Q8mgXCdRDYL/TCe2+Z1yCPRELk+lkA6g==,iv:mavkABwAPXUKg2piqYukclRsAUrpmJmrmet1z9ygkUc=,tag:SDquY+3K6OQlUfPC3IafdQ==,type:str]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZait6NXJicXZFVGZNSUVV
        cGZNZjlUdGQ4MXJMY28yUERmY3Q3KzdVL2djCmxXcE5ST1lKVEwvbkJ1bTA3V0px
        RytUbzdIYUZVVEtLZ3RwWS9ad1VBdzgKLS0tIDZESUtBL0VBNXE4Y2ZLYlNCYmRi
        NHBzeUYrUC9nMGIwWS82eXNUVGFMLzAK3FlBNVEkYM7pR7IlQmDdvLczA2QZqMw2
        EKSbcICY0CFt8ZlautgeIZJtshhF84a3/neFPFjiub4SS8uIo46Wlw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-26T19:06:26Z"
  mac: ENC[AES256_GCM,data:eYLNr5P/JSrcVXymOLo124t38KjWYB4zO9P/zrwwq8lDoX87RahJgxGVhvkIZFW0t0jdDv7O8QiJq95fCAZ6+HFTRvtv+MgI25MfzD2+azhyvBx7o4EQwlsry5uHlYsrOhbYXGzoN+wMUFJU7IVAxG12/f7nPAAmCpGnz1RkDW0=,iv:Buz/suw4WMJqSUvOfoyFEtxkNMz14qKordtQbdK7E6s=,tag:hO6WD1F7nXRg+nt7iOS7/w==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
