apiVersion: v1
kind: Secret
metadata:
  name: influxdb-admin-credentials
  namespace: goriva-si
type: Opaque
stringData:
  admin-password: ENC[AES256_GCM,data:OKVOKd4cxF3ImHa769C6Zff9poU=,iv:4wYjARUFIquocx76Yady4TT3cjB8dma3M1X6sgaBgO0=,tag:yygUSzlSy6Do/GZG2OvrAQ==,type:str]
  admin-token: ENC[AES256_GCM,data:K2J+qucHRGEnSBJ1k6uV+FMsXVDETq3sK6nHnNPdRd+YNwFilxxq1AsEYwLu7apCWt2tsolrY6ZjTmS7/Q==,iv:1Tz2aPRMwvLjVORr1E61HtRj8Lz4k7ZRPCWVSllPZx0=,tag:hqe4M0Q1jka9ib/d4szeiA==,type:str]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZYmtwNE14UTYwejZrTmdC
        SVlib0trWnJSYlk0TGlqcE1BUmM4QXJCTFJZCkVmMzFGRFdKY2NlWm41dkZMc2JP
        Tjlqb0M4c3JyUStkUWlia2l2R2xzZjQKLS0tIGtUc0dENmhhTU1YVFo4MWlpSTJr
        S2lBMzd2NHo2Z2xsbW1vNWFMZWxxalUKt/FPpZZAyDBnxcaJpzhWCepxbXyQvo80
        fYwl/pRx9T7h93XRV+odjQYINNNJN3njtEZmSOr30qsH6wrBmBLnrQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-26T20:02:19Z"
  mac: ENC[AES256_GCM,data:iHQDqf2tyUlIFWGFFi8E6PL0/j4SY235qMAJaIuzhdgDtGE/RGR20eN4K/t9jVO8ka//Ymq57vE5e6KoNdLk1hOC+mv3W/9VPNZvg1trdvy/hG6cR7gxpI6zNIibee3sJA2OoE7W82B5BpaMy45WahRoll6S/5Cs9xUXSmpRwzg=,iv:rVojmJJxmMrDBKNnl8Fie53NdJZ6DU6K6tlxhUDv62o=,tag:tMEloj2HUk2vp3hOJm3nVg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
