---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ww-gitops
  namespace: flux-system
spec:
  path: ./kubernetes/main/apps/infrastructure/weave-gitops
  prune: true
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
