apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cert-manager-secret
  namespace: cert-manager
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cert-manager-secret
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: secret/data/external-dns-secret
        property: token
