---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app external-dns
  namespace: flux-system
spec:
  targetNamespace: avto-masini
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/main/avto-masini/external-dns/avto-masini
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
