apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
  namespace: infrastructure
stringData:
  api-token: ENC[AES256_GCM,data:Wi0Mv1x6c99DUxmaJ/cEVp4nkBX3bxPz9abT6Gyi8QKs00ZMy0RmLw==,iv:eepyXwJtmn7bK5vzyzGzgZNnhxzvoaJwPLAltBNe8iM=,tag:8SIwwxJngPr4kfCSToiqNA==,type:str]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZTZSeG8zSUdySWxuazRG
        WGZJdTE0TFA0Umo3SnA4bG0yUGMya2FOeUVJCnVUdHZKOWs4cE8rbWRmSVUvSkQ2
        UGRjTDh3UXl3b2FxeFcvbC9Zeklja00KLS0tIHhWR0ZadWMweWRvTGlVdWN4RDlw
        VTk5Z0NVNFVEczNNdWJlaUJiZzk0YVkKEgrljM9QR4dWIdHRVdSF1ldWvmMctA2N
        WriKJLs7yQDgsKC10dRB64Jzwbakl8OU8G3KpnIX8HWR/+cdupoYCw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T20:33:09Z"
  mac: ENC[AES256_GCM,data:bBNTS1LW9zkeonbYRxpam64dI/auSD381XU44qZulxnAwTCZ0gZQDIskxV6eOXem9cAaOe6kC0ldEx0a4OaU7xUZ7wT4VWFOxWpPr9B1nTl0gONr3cgy/m+2SKUE17sxHeEdLfFGE9y4CxjWnQQjgNSFW6r50RMbOOGKvjla+gA=,iv:jnpGmd70d1wd51zh0tVP+ZP2kkK9yMhBsd/l9LJfr4s=,tag:kgIqZ33t/5ve5s/V7IA/2g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
