apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
  namespace: avto-masini
stringData:
  api-token: ENC[AES256_GCM,data:O623ud/31zbI+fqmyuDhjerfJo68A3Ga0UII+DGVE/BalZdrwI2TAA==,iv:UYIRQryd2mk8t/W+ydWoLBkQMQ0WeWU+9BkjMR49PoM=,tag:pz6vmyOLaPGoGwvFJhRtFQ==,type:str]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cU9YNTJvS1RIdFFCQzIx
        TnZINHNsaVY5SkJLVDNianorU0M4Wm9Wb0FFCllmaVpPTHFjRTlkaGRidXZkRmsy
        amV4QzVwYk1IUzRyZUYvQ1p2d2drOHMKLS0tIHhFWjlXSDN5eXVhWDcydEFvZUZV
        N1JuT1p5TFpUOUVEc0NBcEdNMkplZG8KhgfASu2LOHwgyVyEgTkIdGFeOoeJG5+w
        UonRkCxYPgfEGA6XqQ9wYd/R7CDhWplOOoMOyu/gkI6EmkW6LrPqCw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-31T08:35:54Z"
  mac: ENC[AES256_GCM,data:wYKGg++YRjaTqwDOie1/foY3vDQUpMg+IJZk7UQjqJkIiZdcqxIeRWuTgVymexPGV6hfq2nTk6vRPAqPL08XpGW+0tTHPLR8BXINgtUtd5Dy2iTphpo+9BDq8LnMUCRGUaiEVdrpZhwsOr4nkFXmiRe06wuCPIvy3E+P1daKn7c=,iv:eiuuwab+OIyaZsIhr3utpcIX58src9vIj5vESOjNpJA=,tag:4SIUk+5eSTp/FAotQAw3Tg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
