apiVersion: v1
kind: Secret
metadata:
  name: s3-creds
  namespace: cnpg-system
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:lBKXulaxXfgzvqkRfTx2CaPIyMc=,iv:mTvf40lrtJWcYRi37yxYVci5PDg8FCaFy42yndsXiQQ=,tag:oGRIY0+lx6Honpfyx3Uz5Q==,type:str]
  SECRET_ACCESS_KEY: ENC[AES256_GCM,data:dBauVdZaxubgBHpZVS/cGcArNLgXtf6eeUBqmOpYWdkXEtxphl6MjA==,iv:+PgcVrUNmQWjJ9TiNS+9/jL3HJ+BR0p52CTIW86EIIk=,tag:Vt9tnjTtjWoN2huaITEkfg==,type:str]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjaVQxUk1xZEIxZFRLOGto
        a2hrRG1rZk1oeGd4NktuNUtTUkhJelU5ekJ3Cmx4azlaKzBwOUFudDRuYnkvQjly
        ellyREd4djU4OTBON2ljMWwyWGtnWDAKLS0tIGcrMlp3UCtoL0Y3V2lrTkpyc3M5
        MzhBUGRGa1NyOE9ia0hNZDR2T3pFcVEKg4W0L//J2m7izP1rlejS46TLKpss3Ijv
        TVZ3eJmTce6y/IsQbiJ7kaDHBFouYv3waDUMkxkDkgbeX3hgC32j1Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T22:13:36Z"
  mac: ENC[AES256_GCM,data:vWobFFmQL1tLCjUC4fqOqHsZegCxGJeG9q/iNdCwuyTDqEsowx4SPCj1Vz33Ri9XQ7tG/uKgY5caQgN8m+vmIvCe56iZ4l5EUNbNe3fPrZo/1Krnqulv+zfepAyuw7rideq7UrPu6Uvd7W4IkgpWzcyKi+97y9QhRkfr/gmS1B8=,iv:mTeYjKECcX6lkdWNuhdSyMSJx1evgir2tEnFWaqZJsA=,tag:OmB37YMVx4iPCNjmpop89g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
