apiVersion: v1
kind: Service
metadata:
  name: avto-masini-web-staging
  namespace: avto-masini
spec:
  ports:
    - name: avto-masini-web-staging
      port: 80
      targetPort: staging-svc
  selector:
    app: avto-masini-web-staging
  type: ClusterIP
