# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: cloudnative-pg-secret
  namespace: database
stringData:
  username: ENC[AES256_GCM,data:8Rg3WEWmcR8=,iv:qR//wo4/rTXMkLzq+U1Iug16QKPAFoINEgFPSteLRwY=,tag:ouYiFKaf/Itk2zEBXnhRuw==,type:str]
  password: ENC[AES256_GCM,data:sxdm9K65ruo+5btDdSw=,iv:QhLeBQN8+OtcCeNWZ6wc+UPGPl8T2ncTLBlj3ZOii6U=,tag:B9vlfEOREKj6axGIhaTHvA==,type:str]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Y3pwL3ZEMWg5dVFuU0hl
        REFHQ3dDeHdUdWlHcXRjRFNtVWpqeE5uNVU4CngzV3phMzMvM25BMzFSbWorUXlM
        QUM1SmxLQlRuNyttZ3ZISjllYTl4QjQKLS0tIG5oQk9nM0tnNXFldFk3RUlnenQ5
        cWxJcVZBSG8vNEN1MHhIOTR2eXB4Q1kK2lmTkf5wkG1/K8xJVLihrwzSrSk3rmIz
        8IZ0E8W7bxNnPLixJAmuJchpgY/yNVgwew3W2Lot1hf6hecLkhHlPg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T17:45:14Z"
  mac: ENC[AES256_GCM,data:9W7TVMLhg1p7Gv1dJ8ccXQz1pf1KpajEuvUM40ECxinJOxaP8u7YPXfOjIc31TqAVNHuggzHUAkfzBmJwsrikXkAoWvKg8/qMWnTpZtRg+jTkCau757FxAinr33y386x4CmbTsxDBy3nY59H3rKp7N+6Qcg6PLtJXCgp2GFLQtU=,iv:lCaiL0txUeudel3QH0vXl5OAGU4YCT1BOiDDOSai7jE=,tag:WBBROUtk+/t3tr5u7s5dUQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
