apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
  namespace: network
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:kql5Y/KgY8GeE7DkTmf9wL6t3moeBxF4TQ4kCeDBc75Oofdk,iv:133Cy63DPgN70OsBz6vQ3TjkrKmQf8HrUehyyPVmHWo=,tag:ahOQ7/i+u8/K+sPGVwWNzA==,type:str]
  credentials.json: ENC[AES256_GCM,data:0375KzF1bWHcNq6zESihvMoRPZsxCC064CC6s/RdtoP4bZrjNVpqgQrjZvyHdGwBGgyLx7lStvcLoCGiV5UNqRaNq9zYLA9LHzgEmNab1HvkqIIpVoSPjIr9fGH6PySn2vd90eKtZzVP7kLFuRCjZ5ADKHxTITxAAaURRqjeux/kvFpcHopjURGopbKNt43YIBbHmdRAI60pJYQ4KXLh7ELqAsGABVWVyUXaf7qxMhk=,iv:EMSuEqxT6XWVk0Kf0Q7vnJ9hed0NsHtsXBFkI17B3Oo=,tag:dPh1xXBRwu65YBuFDG8Uzw==,type:str]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCS3dPanhEYkliUjVZVDJP
        MFU2b3ZFZXBKOEJsVmpSMFl3VjZQc3FnUVRzCk9ic2V5c05OMi8veVFMNGVBRGpF
        UnY2RWNlRUdmTW5xRU41VWZ3MmxWSHcKLS0tIFRkaHNqeDZ5Y2hramxaRGpQTVRF
        TGdnWGo0aTVGN3RTcVFGOXlNNmlKZ28KwBHGBJGjDaPPTYcjN0NOd2M+B57YBdy8
        ZA5WR+DYrhsiGu1RVJX+y+vFiNxaAhD10mDEK4JHYTwxzX653GgXYA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T17:24:33Z"
  mac: ENC[AES256_GCM,data:3iJJ3Oyp1/QMFehjmi4LO10klg2v3yRIJxTeOJfBxBozVN+I60yyo96XmWXGAWZ2x/y9v4xjojJz34ZcB8TFaDcCD/GPvIxrrrh+voLi9jzwNlRK4bMwvmu/xmNPffwRVK7c5tZgqclFG3KXqGDK+l0BET+CKa+uBXoEZOqbb7k=,iv:pTkxe7KNPkBSZ8wsUyCvDQjviS2IbCaw9fuWOll5ORc=,tag:YnzaYgi1wtIVBiLz2tk1wQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
