---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-avto-masini
  namespace: avto-masini
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.15.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: avto-masini
  # install:
  #   crds: CreateReplace
  #   remediation:
  #     retries: 3
  # upgrade:
  #   cleanupOnFail: true
  #   crds: CreateReplace
  #   remediation:
  #     strategy: rollback
  #     retries: 3
  values:
    fullnameOverride: *app
    provider: cloudflare
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: external-dns-secret
            key: api-token
    extraArgs:
      - --ingress-class=avto-masini
      - --cloudflare-proxied
      - --default-targets=${SECRET_AVTO_MASINI_TUNNEL_ID}.cfargotunnel.com
    policy: sync
    sources: ["crd", "ingress"]
    domainFilters: ["${SECRET_PROD_DOMAIN}"]
    serviceMonitor:
      enabled: true
    podAnnotations:
        secret.reloader.stakater.com/reload: external-dns-secret
