---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
configMapGenerator:
  - name: glance-configmap
    namespace: glance
    files:
      - ./configs/glance.yml
generatorOptions:
  disableNameSuffixHash: true
