apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie
  namespace: uptime-kuma
spec:
  reclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi