apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-secret
  namespace: external-dns
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: external-dns-secret
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: secret/data/external-dns
        property: token
