---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns
  namespace: external-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.15.1
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
  # install:
  #   crds: CreateReplace
  #   remediation:
  #     retries: 3
  # upgrade:
  #   cleanupOnFail: true
  #   crds: CreateReplace
  #   remediation:
  #     strategy: rollback
  #     retries: 3
  values:
    fullnameOverride: *app
    provider: cloudflare
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: external-dns-secret
            key: token
    extraArgs:
      - --ingress-class=external
      - --cloudflare-proxied
      - --default-targets=${SECRET_CLOUDFLARE_TUNNEL_ID}.cfargotunnel.com
    policy: sync
    sources: ["crd", "ingress"]
    domainFilters: ["dnsk.xyz", "${SECRET_EXTERNAL_DOMAIN}"]
    serviceMonitor:
      enabled: true