apiVersion: v1
kind: Secret
metadata:
  name: s3-creds
  namespace: infrastructure
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:neGUx8fjiswVwBcuenjLQVfDvEg=,iv:LFEKss1y7ywnACIpjqHSPp/H0PJHgVYgf52NN3UOCBo=,tag:VtOGpQ27sVrwr6xfOKNACA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:zl8uN0R1GgOQ5kPFoTRIwPQGS1KK47JFjMiRBNLaJNcyyLbTcCaskQ==,iv:/hkiouxA9t4wdvJRz7HvLOaxtwT8VNaxYwRw8dxFGvY=,tag:U7gI00FNR9DPSiHi5SPSOQ==,type:str]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSDZ5MXd6djB1SjFaWEt0
        a3lDaXRFV0R0UlBCaElMMHpvajRxZFBJcDA0CmZBcWFrUlRWQmdmVUtYclI5U3VB
        MHNYNWpRM3JLd0Z6aG5MejNidW50YVUKLS0tIGhQeStSaGVvckE2M0xsUjJTZUY3
        NC8yRzdXZlJhSjY2OEFIOCtqNkFCZFUKZ81FehyC8v3bhIIECmK0o6lZwpl6HRxJ
        OSTAJ8AvVLoUmGi23CNVqekyxcyrLpxuFs7/Z+VJoOWCvQlNtSWsuw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T19:56:50Z"
  mac: ENC[AES256_GCM,data:+QhbrJoXk9S6wxheuFKBX2SKcgDIK/uVCb501AHbfM6PCXVNHdR8HtHubohf9sqc1a3kSuPFRa520HckFLYY91sVcTNvpesZHw/JdR2a+wI5eDKEJQDmh3thSQsWH+YN16eAv1Xy8QkEtaz9DDvQFjHhnwqXYByBbr5LnMz43zw=,iv:TVLFUP017CvMaxTOCpScTrv/nIMqhNbxOLmOsRCj5xE=,tag:/LK8VlpHXdcJElA850U5NA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
