apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
  namespace: external-dns
stringData:
  api-token: ENC[AES256_GCM,data:O623ud/31zbI+fqmyuDhjerfJo68A3Ga0UII+DGVE/BalZdrwI2TAA==,iv:UYIRQryd2mk8t/W+ydWoLBkQMQ0WeWU+9BkjMR49PoM=,tag:pz6vmyOLaPGoGwvFJhRtFQ==,type:str]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cU9YNTJvS1RIdFFCQzIx
        TnZINHNsaVY5SkJLVDNianorU0M4Wm9Wb0FFCllmaVpPTHFjRTlkaGRidXZkRmsy
        amV4QzVwYk1IUzRyZUYvQ1p2d2drOHMKLS0tIHhFWjlXSDN5eXVhWDcydEFvZUZV
        N1JuT1p5TFpUOUVEc0NBcEdNMkplZG8KhgfASu2LOHwgyVyEgTkIdGFeOoeJG5+w
        UonRkCxYPgfEGA6XqQ9wYd/R7CDhWplOOoMOyu/gkI6EmkW6LrPqCw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T17:11:12Z"
  mac: ENC[AES256_GCM,data:QoyTJpfRUFVcPbydv8D67oJosPjQ2+z9et3mA7maBg1wFCnLKQE3hKw55VOAnQmRWJVe9BDUkj00TWW3ZUC1/JacoUg/AjKWcPWd7zL0yodMOmhyiM/r05xe/uqZ7HmYUSKelc3R4S03I1E+GYXi2JHKDsjendP6w2lJmMQyjfc=,iv:d3OKtsUhwJgUjNu/UHy0oJe4BLR07lzn4gW16K6d0wk=,tag:qgyGSQG1RtQrOkez5KrDeQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
