apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: observability
stringData:
  AUTH_CLIENT_ID: ENC[AES256_GCM,data:odyXdpMKdHonvAG8CIkvPIP90l31q2JXE9J8hyhE3rP+D7TrmBF4sA==,iv:SUdsqIlEc+I1z+SZDYhKQMrFcIYZ8N9zxlAm8XoeP7w=,tag:beOSH5NSladuXX1KovMxng==,type:str]
  AUTH_CLIENT_SECRET: ENC[AES256_GCM,data:QhRPm4gsvSUQq3JDw1hjK0b9UqHyOoyjm3Hqo/CLWToGUFNUpQH+GOQPac05VMYbEszbZ8t93rAFc6c3Ut+tOyHuhKg7kU1jOlu+iuFEM9PLmmOt/CkuiU4Al/1a/0YSO0PNoN3JWnIjB17NKW5Abn/bxrz/MtxgLRC0rqGXLMg=,iv:hVr22mewynSdAkTFpD9Z5ujtA/VCcCSM4wq0WPBlhYw=,tag:fUQ1Lf2oAXNSQ01yf8fWrg==,type:str]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZGlVWElFQnZOYVlXckww
        ZHVVNExNN2xZUkNsaklNVjlGQ3dMU0ptam1vCk5OQnFPZmhoNjd3ODJvZ202Q29Z
        a2tYc1MyamFKeWpZbkF1ZmNsWkh2OE0KLS0tIGpKKzdmN1BJQ3NsM2lHMHFXSjlB
        NDZxaGM1WGhuc1R2c0liNE1KV0o3eGsKEKL1KgZydxm6iz/46zUeoZq9488YRFta
        mPjBjLGxQjJfIemJa4N/kZaZHuxhqpwHWcUp7Xfzp63NfNF3uaeBHA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-03T14:18:03Z"
  mac: ENC[AES256_GCM,data:wNTCzr8jog9zJheQkhPb4v8POkWJYq9sBKzxT5agZzEa7/FMSlaLZioCTPyMhWuc5MQSOLG5P2wJHRwAMD6pqw/sdID4rGY6UVYcTncrbCi690c1mJJ3dHKH2tKj+AWL2n84dYnnSBCdxrwvKn3qRbE6oYWAwgJo4hgBL/qEXTQ=,iv:siNoS4xh5fpfCZP5zJg/wSxK9/1jrPvdNtR3MQVngmM=,tag:15yWSqm2OsPRTNJz7PcwDA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
