---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app metallb
  namespace: metallb-system
spec:
  interval: 30m
  chart:
    spec:
      chart: metallb
      version: 0.14.9
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: metallb-system
  values:
    installCRDs: true
