apiVersion: v1
kind: Secret
metadata:
  name: authentik
  namespace: security
type: Opaque
stringData:
  #ENC[AES256_GCM,data:dyh+A4itWODSXNU2IKsViaPSTWEwkhwjvn2JFvU=,iv:mrn4ez1SMl2FMd3oD2hl1Gg60YGNKZ4kG3cmRLOg624=,tag:S7MOWAmIiNZq5HGckHY8dQ==,type:comment]
  AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:oS4RegSuHhuMKeJlReO2K/vf445DA+0k5eeGsQdJupEkAoXlc2xp3DEewrr0y7PYW0t/NH7h34C2ygfQTCoFUGcxiW8I31ZSjpFN8fVhv2s=,iv:2yVy+vWNmjL5pfBq0/irquoKMFmOaRXS8XG7qRMVTJ8=,tag:/lnI/WwSKX5eFgH2pjXAFw==,type:str]
  AUTHENTIK_ERROR_REPORTING__ENABLED: ENC[AES256_GCM,data:Tfzv/Rc=,iv:0T5W8fZLqzZFr3dm062jxYcanaSCyyXcbVSag4Eyzm0=,tag:2amR9X97SQXU6ey9wnN9ew==,type:str]
  #ENC[AES256_GCM,data:+doMcYJB7hSi5phJidNOvYmMEoRJnQ==,iv:GqR929SwpJMQRWh7Ax3ijjX66nuM6q/8VsH30Y2eIbA=,tag:efGLZQRbVyhFZ/BE2qvnoA==,type:comment]
  AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:c47FS7/e1NqwVpYLFvIh6xJwj8/vibCVLY/TQhdMWxwak4bHlOsCOw==,iv:Wxat6SHJwq9k0XQ30hld8lZvaCJbhot7PyamxzEhoSM=,tag:YIIq+irz8fsSzPYL8xcXfA==,type:str]
  AUTHENTIK_POSTGRESQL__PORT: ENC[AES256_GCM,data:U/dLYQ==,iv:51fmk425B92+pbxHrgcst+0TKshQZc44K067KO4Sf8g=,tag:hPqkRYeiA8hXdlLLURcgXQ==,type:str]
  AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:D95mbI33DEnt,iv:gk3yol5khd83+WfhNVOvae+TMzex4lHr+r30JHFYaSs=,tag:1gQSFXLCp0XO7X3/aHfW/A==,type:str]
  AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:f4xUcDDLnBxd,iv:MHn4R5sKIjqkHf6BVzueKGTkEKYzG/XvtNDMZPunGu4=,tag:sfaFoFa0K3rA0/4WVtXh5A==,type:str]
  AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:Zg4We4jErOQt9YB3jjs5W0gApSEtag0YBIbZgscUQm0=,iv:/1pJpG9eALKy9van3mpn7ycJXslGMgW6RJoovcqN4EA=,tag:e9HtlbP5oiY80L8VGhgB2Q==,type:str]
  #ENC[AES256_GCM,data:+zMW3gJxJW5YFOwxOslB0i3TzoQfwl7gv9Sif5qzpQ1n2g==,iv:9+TQ0hhF450BytUH9QbOk7CT0vKfXigEp+hey3n9HEc=,tag:8SQ77qd+BkNGhKaVLz5OGQ==,type:comment]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:t4uzs9N4oOphT0nDEShZ07AkmRWTTnRtcLjU1jU0TrI0MN8UlkBmFQ==,iv:mtLEG8fOtifryyBIQ6UwY+3Wb2ACDSpcv0fZq6oKxt8=,tag:wgJNkLx+AjWDPkj5i5Kbyg==,type:str]
  INIT_POSTGRES_PORT: ENC[AES256_GCM,data:Isvimg==,iv:ytpzlnC0pPq1Pt/tQQk8f0I71q+gjGV1+4L7QdZJpaA=,tag:o0jw7ZkuedyqM2o89O8SSw==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:CqVBGieWyDSS,iv:wptRGEUeEkE5xUSl4c94F8jcyiU2WQjaB7v9UZ8E+qE=,tag:GikwPsu0JMRGgeIJS0HwZA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:h99OVscZTc4+,iv:EqWm0U7VBXai+tzk6/GIdktEg58YFhRXgnLOxQlW658=,tag:vtHv+um1nlIWOgLvW6KG/Q==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:iTQr19mm8zwychykRvcgP9Z377M5wVA13Gh+Tqm7Iuw=,iv:/KN+wE9xJINjrrBxW9+tCeEBEFcYjOaTwliWbgccnlE=,tag:STPrb4MhF2mBN/lvq1QMQA==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:GCo+Cq62ODY=,iv:tYkbqI6vj5vhx+KQ54wGtPcd2Wh6XZWKOjddznKd/nc=,tag:1GxhF2F9gBr54nVCjQHY6A==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:Qg1+pZPOM0OSOKOiK78=,iv:IYy6Ky9gXCmKxEv/QxBbUX7Ya/coo/qw7DDJsu9UNkA=,tag:7dgLwajov9el1eEaqJFISw==,type:str]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIcitjZUhuT0s5ek53RWxo
        M3U0aFlHN1Z6ZU90bUhHN2hmN0xOWWFCWmxBCm12SmxSR2pZbVdJY2VISjBDRm5y
        T2tjWHhkSks5VnhIRFl0NGY0VkZ0blUKLS0tICs2VEoyWE1kbUk5MzZ3RnErRG5D
        bEdYV2dwZUcyZnJuN1lpMDVVVVk4dTQK/eRkn4jd7CQPO4hGe8QjVlfxF/yTvx/h
        BLilN3oAkFyU1DiQCV6kaqecN2DIoTCwAjyCQgCOX7RzBWdczvKdSQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T20:42:23Z"
  mac: ENC[AES256_GCM,data:mGCdtoPFz5S+wrBS4fflboP9BdLssJEh35v4wb02E0aHSQZh7w0zKwA3WPDgSK/GVyUBYuNfsvh/giPCT5kMUejIin+1D2YdICj4cmpxNXcCzJz8i5EjcmqOrn1lfjdpVKQNJLwv9bvwCIcstLySux1h+5Wn8iAq4WVLFR7Fy4g=,iv:A4rJST84DQT5nYcnl2qMTlOBSaP7Dk4jRyYM/syucrQ=,tag:dACNiqGqO6CUpnXujCqMFQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
