---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-board-client
  namespace: budget-board
  labels:
    app.kubernetes.io/name: budget-board-client
    app.kubernetes.io/part-of: budget-board
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: budget-board-client
  template:
    metadata:
      labels:
        app.kubernetes.io/name: budget-board-client
        app.kubernetes.io/part-of: budget-board
    spec:
      containers:
        - name: client
          image: ghcr.io/teelur/budget-board/client:release
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
          env:
            - name: VITE_API_URL
              value: "http://budget-board-client.budget-board.svc.cluster.local:6253"
            - name: PORT
              value: "6253"
          ports:
            - name: http
              containerPort: 6253
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
      restartPolicy: Always
