apiVersion: v1
kind: Secret
metadata:
  name: pg-cluster-secret
  namespace: budget-board
stringData:
  POSTGRES_USER: ENC[AES256_GCM,data:3ues2lk5n/A=,iv:8IRATkABA+bYBBS11kia4hA1Uko/IJPJ8o0tD3FxbM8=,tag:CRvh7laqXrebb/qF4EBCnw==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:+3hoLMG8bL2Gs7Y=,iv:wP7FxeEpi+qS2XwGs1RtcaHoLMZCfrqKsA9T31xTMz4=,tag:KXa4qcCi3nG54Hk71FlmDg==,type:str]
  username: ENC[AES256_GCM,data:zWhJtTvZyUU=,iv:AHx6WNQvW8qTJSx/kCJA/QHBtKFfmwFl8jicMQtmy6o=,tag:ec7Dmr85BH+zRUF39z4ugg==,type:str]
  password: ENC[AES256_GCM,data:/gpjOi2Yqp1Hj5k=,iv:R7U6e7RKRbMtWsN9Dezr92vtuxu9Qqq3AO5TMN9yAjY=,tag:qouJ1R4VkPVyK/72lS1fFw==,type:str]
  ACCESS_KEY_ID: ENC[AES256_GCM,data:2KyGkFECuIeM7R/Ey3URwyPG39c=,iv:ATbeZYU9qbCnx8bD6qy8mTSPR/1bKZQbeUf9IPxOvUM=,tag:E5qecJ2KtLVq/+CKEafjHA==,type:str]
  SECRET_ACCESS_KEY: ENC[AES256_GCM,data:xd018NR+2AxQCDznrgVZAl1cHTRwXSBPq8BoVIPk07QqBGPfLZerXw==,iv:2JjnfNhf+Xp5sAFF0wt8/Ke+1ionxRfR3q2UcUuYoHo=,tag:bXNwcKZ00VhwIxHg3VSwSg==,type:str]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQ1NjUEppUnpZNXp2VkhH
        U3VIOUZxdkxsR0VuTFA5UmxPZWlUSWdYMEJFCmpVMHBCcXFPMWUvdkZscXZId0Ry
        Y0dDaGJiRXk3MkszUndhczJJYUd4bUkKLS0tIG1DZ2JYeEZFN2RidU5vSklqQ0FH
        dGJObnpYempUeDFVZEdBYXRIb09aQ3MKCvwexrdag4YAwI/AwI8/CdSf/763CL2g
        V4qj4bLJ8Q0P4YfA99jVYuhIORyPKH6nSUKxz8D9nmiCVvGQAokMfQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-04T22:29:55Z"
  mac: ENC[AES256_GCM,data:7EitHyGRBG7/RqDk7k711V9lnhPnU/usPwxTX2lVvxAJp01hC0+KhkiExUhJ8lW/EA2xMbH+ic5Q+nmhJrx/SPpokN70ju3VtPDp2LfTwgiAtCP7CklVLNUiFj5JDWMoesoJm7XlIrkpKXZlwfgsqR2UfxjJE4sIY6zuROceAy4=,iv:0arLNU0nkHwvmSzZ7Hiaf0AiMiCBYay+f2yGlD+5tnE=,tag:JHEQ1GnOB5SzrGq6ngGUiQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
