apiVersion: v1
kind: Secret
metadata:
  name: pg-cluster-secret
  namespace: budget-board
stringData:
  username: ENC[AES256_GCM,data:zWhJtTvZyUU=,iv:AHx6WNQvW8qTJSx/kCJA/QHBtKFfmwFl8jicMQtmy6o=,tag:ec7Dmr85BH+zRUF39z4ugg==,type:str]
  password: ENC[AES256_GCM,data:/gpjOi2Yqp1Hj5k=,iv:R7U6e7RKRbMtWsN9Dezr92vtuxu9Qqq3AO5TMN9yAjY=,tag:qouJ1R4VkPVyK/72lS1fFw==,type:str]
  ACCESS_KEY_ID: ENC[AES256_GCM,data:2KyGkFECuIeM7R/Ey3URwyPG39c=,iv:ATbeZYU9qbCnx8bD6qy8mTSPR/1bKZQbeUf9IPxOvUM=,tag:E5qecJ2KtLVq/+CKEafjHA==,type:str]
  SECRET_ACCESS_KEY: ENC[AES256_GCM,data:xd018NR+2AxQCDznrgVZAl1cHTRwXSBPq8BoVIPk07QqBGPfLZerXw==,iv:2JjnfNhf+Xp5sAFF0wt8/Ke+1ionxRfR3q2UcUuYoHo=,tag:bXNwcKZ00VhwIxHg3VSwSg==,type:str]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQ1NjUEppUnpZNXp2VkhH
        U3VIOUZxdkxsR0VuTFA5UmxPZWlUSWdYMEJFCmpVMHBCcXFPMWUvdkZscXZId0Ry
        Y0dDaGJiRXk3MkszUndhczJJYUd4bUkKLS0tIG1DZ2JYeEZFN2RidU5vSklqQ0FH
        dGJObnpYempUeDFVZEdBYXRIb09aQ3MKCvwexrdag4YAwI/AwI8/CdSf/763CL2g
        V4qj4bLJ8Q0P4YfA99jVYuhIORyPKH6nSUKxz8D9nmiCVvGQAokMfQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-04T22:11:20Z"
  mac: ENC[AES256_GCM,data:ykOz8Wd10hhio+l2LWk9vS6rnzbY4Lboe2iwJLhg8fs0KyvU56b8m/uSaObQLBlfVNjpGc4ofygRGkZgNvRSz6CS0fFW6g2sBwsAdPTj5u9Krtj1NmbxvHStQb2C4b14SZ694ND+J3VUEaGFPljOyP2NnIZx3Znpo0Wqr1jHTcA=,iv:8uCvgK41qYPff5uq91V0lf5ZIlXz0LJ7hGJZqnsbq2I=,tag:64G9g/pGzhvUxaxh4BUW2Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
