---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-board-server
  namespace: budget-board
  labels:
    app.kubernetes.io/name: budget-board-server
    app.kubernetes.io/part-of: budget-board
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: budget-board-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: budget-board-server
        app.kubernetes.io/part-of: budget-board
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.36
          command: ["sh", "-c", "until nc -z budget-board-db-rw 5432; do echo waiting for db; sleep 2; done"]
      containers:
        - name: server
          image: ghcr.io/teelur/budget-board/server:release
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: server-config
            - secretRef:
                name: app-db-credentials
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
      restartPolicy: Always
