apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: observability
spec:
  type: oci
  interval: 5m
  url: oci://ghcr.io/prometheus-community/charts
