# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: cloudnative-pg-secret
  namespace: cnpg-system
stringData:
  username: ENC[AES256_GCM,data:zsQ739He39Y=,iv:HR+37xHAdjzCn16tYbMhl78OvdSBMA7/oSgExHHrGb8=,tag:8BtN53W3OfBmvY467as1ig==,type:str]
  password: ENC[AES256_GCM,data:iakn5nzVdggPgACVrUo=,iv:I3N44IK3M/qKSlfYz6QgSTaUJUQDsnHxxno3aiC4hW8=,tag:AKKl0TqsO/krpqYKcS8Y6g==,type:str]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWnRLQVg4Y0N1cEJqeHhY
        YTZ2UmZsOFRGV1VJQlhCeVBxVkF5YmU3WDBVCm13bkNjNUg5RHozbFYvR29DZjFk
        ZXlIT0RidDNubFVPbkkzcW4yRkRFcUUKLS0tIEJEY05xMHpqY2h6akN4cUkwa0dz
        ZlJJLzRQRjFjbDhaVm12QUxjd3BpcHcKhHVQAWXYky4XXxJJnCqKnGUYkBakMZfc
        Gs/xgDG7WgO6h6CxMjaUahZUcZZA/6R9wm++1xxdzSZou0b0XXco5w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-13T10:01:32Z"
  mac: ENC[AES256_GCM,data:JlV2tomDu6IDiltrVIbFc0jlqYGMtDOJn9N4ib9+E6aZ1yHYl8qRe2kd9uGmhEPiPoUj9kWn1n9mTmnThj7Yp4FOuMKn8b2cWfmyni8tM0E8qUXSDvZWZdTYb2A8aU7/DdCYQBiI1dDViXF511D/CBr1UWxa/hornxan63XU/Tc=,iv:VGb53J7uImZmWYyv9MsPDtITHsT96ZWPCl3hWWcYzdQ=,tag:Vrvuc43GeEpPcc5ZjOkyww==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
