# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: cloudnative-pg-secret
stringData:
  username: ENC[AES256_GCM,data:zsQ739He39Y=,iv:HR+37xHAdjzCn16tYbMhl78OvdSBMA7/oSgExHHrGb8=,tag:8BtN53W3OfBmvY467as1ig==,type:str]
  password: ENC[AES256_GCM,data:iakn5nzVdggPgACVrUo=,iv:I3N44IK3M/qKSlfYz6QgSTaUJUQDsnHxxno3aiC4hW8=,tag:AKKl0TqsO/krpqYKcS8Y6g==,type:str]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWnRLQVg4Y0N1cEJqeHhY
        YTZ2UmZsOFRGV1VJQlhCeVBxVkF5YmU3WDBVCm13bkNjNUg5RHozbFYvR29DZjFk
        ZXlIT0RidDNubFVPbkkzcW4yRkRFcUUKLS0tIEJEY05xMHpqY2h6akN4cUkwa0dz
        ZlJJLzRQRjFjbDhaVm12QUxjd3BpcHcKhHVQAWXYky4XXxJJnCqKnGUYkBakMZfc
        Gs/xgDG7WgO6h6CxMjaUahZUcZZA/6R9wm++1xxdzSZou0b0XXco5w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T22:59:56Z"
  mac: ENC[AES256_GCM,data:TRJaarJDhg3VwIjYRx86FFFEpIZoowmTKmi0dge+h6XM44IuHopLZd8Fi0D5d8RESklqyCbNLQq817DlpM0J+3+dXxWqzrHCZAPtFV7itJ1AM73YMTNQYHwpY11wtwwhPDCR9eRj6T1AdkOH6f4oeyRnnxSjSIjYa5vXKIOwF7s=,iv:CM6BpKFkkhzrrgL1dLPoqIDtjgJBjsGh4CYy6WwkjIY=,tag:/pnG4q8+tlBbYP2emR0eBQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
