# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: cloudnative-pg-secret
stringData:
  username: ENC[AES256_GCM,data:GvZYpA==,iv:lEQymLgR7vDHBAtUn3aDlpgULxcE/u8SOTAOErvvq7U=,tag:QfP6nMDTsZI416649zuDBw==,type:str]
  password: ENC[AES256_GCM,data:iakn5nzVdggPgACVrUo=,iv:I3N44IK3M/qKSlfYz6QgSTaUJUQDsnHxxno3aiC4hW8=,tag:AKKl0TqsO/krpqYKcS8Y6g==,type:str]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWnRLQVg4Y0N1cEJqeHhY
        YTZ2UmZsOFRGV1VJQlhCeVBxVkF5YmU3WDBVCm13bkNjNUg5RHozbFYvR29DZjFk
        ZXlIT0RidDNubFVPbkkzcW4yRkRFcUUKLS0tIEJEY05xMHpqY2h6akN4cUkwa0dz
        ZlJJLzRQRjFjbDhaVm12QUxjd3BpcHcKhHVQAWXYky4XXxJJnCqKnGUYkBakMZfc
        Gs/xgDG7WgO6h6CxMjaUahZUcZZA/6R9wm++1xxdzSZou0b0XXco5w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T22:08:08Z"
  mac: ENC[AES256_GCM,data:Co8NQDwE1CdinkQPKg5q+TR2OyJ6RBsDqHUxIA2ooCctsP4hBNrl7X47Zo9UdcsY0d8X5vgy3TCb/PBVl7DTUc+rPfBZU7dJAA2vZN3BmReMoujKoTE8vRV9LqkIqVoj4gJsBVQ/ICGrq+NNDaSlbc1xgXQ65+N0t4dMZNNziPI=,iv:l0qnohyEg7Gy4lSYbpg+2aUQbG85RcJ9j7UnRbzN03w=,tag:l6nMd04XVZkdI/nHOSHBjg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
