apiVersion: v1
kind: Secret
metadata:
  name: pull-token
  namespace: web
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:1RfSzj9LAbG+W9PTINaHURWwIibGwtA2Z5yDLdJdD6Lwmp/HxuVfAUwZ6lDAxG9HP3YToi575Ib6y3q+y+5MYOOyf9cCDLkQwrcKef18k8WJC6kKDOUx36o9YuaOdjKBtv7oUWae9PzpohptepwdRZk5GWv22rGeyjyU7yt7Ntfgb1cZ64/mWc3s83XmEJNDVqC2evBK6Ftnl8w8BDGlXwisoxbROMcjnP+rQjwII4Hnw2DLFSmIUE7lxr9ptN2aFqa6qjGZGe7Cr91lAe/7fH5XHgEt4BOcBIsYJz5/1uz+pohjKYwGQlF0KMri535x,iv:6lZH0QoKIFI55GUCEsm2kVh1S9ruHTmlThxd3zQW9hc=,tag:ScT0HY8D0T3nTeV2m8fB4g==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSTZkVGlmWmdiZ2cxcHU4
        a2NldnB6bGpLZUNMNzBDeGFoem1QRGJJandZCjVCdDBoaVBsVjh0T0FWcUcvRDZY
        S1I2NXZ3NDltQzJOV2ErRkY5QzNuUm8KLS0tIDlwalZTZnliN0tiZnV6bjhvY0c3
        eTRkTXhydFM4Q080ZFBwWjROaWJ4N0EKYqvuweh3TX0pe84I0edMSCCCe0vvVFGe
        7S10AIlODjB9AJJKAxCEy8bD07AkJnYwQAaCXZFdhT4s+cj+cetajA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-23T17:34:03Z"
  mac: ENC[AES256_GCM,data:n4S6YHXPpykuDFS4Lq09op/wYSKwfEhPvQtDN1waSeQ44JTBv6UKqO8SLL8Viph9Z3vt2Ur1f1thbxro4ZMHA59oD/sGStV7U8dexCXav/PT2tX7sH5pp6XoVvWYQHXV4bNBKKxTj/VXhQYTuczVrHuiAXE5nseDeAYJJgXHzFw=,iv:jowPQXDGDSuZXp47jTI/1hSobnQ9SqLmFYB+ytJBd+M=,tag:EcI7ePyfN4QHWW3ttAkE2A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
