apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_ACME_EMAIL: ENC[AES256_GCM,data:11oKg4EqlBYgOHXymoPd/Q==,iv:1VKJTrcTuN2j9cz4rlRLg8/Fa/oAkQu2j4YHsD9hDQo=,tag:/QNETGKjP0W7mfXGsTXo8g==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:eHSiGmcv0oYbYUYFdF6AfJW120yn8wDm9Y7PmezhC9tnq9LK,iv:muBdp2drBPDel0GlYdKOeAQbtwF5hmVJJ8gKpRR1IMs=,tag:CVpJ+LktRlOOZxfjFNuEtA==,type:str]
  AUTHENTIK_KEY: ENC[AES256_GCM,data:jA+z3EqI+TCPO06DcCGa/MWyR1H/NW9G4TFZQ7J6cVTaSupaPb2Rm2YVmrq1EARYfJuydESOTSSZX8G9kq57kfWcT+nLGgJ6WnQ25498Zmw=,iv:Gt72EklNHaVIQhs/d7Q+GORTTPSQpMnde5Ht2MYiBcY=,tag:jw7LvSkyl5O/9iVwF5Bnhw==,type:str]
  AUTHENTIK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:gOxzgc9+NkyG7sOUJCTm,iv:mwQs4TWurrj06w8lxRIRE60VyolpXVNsMck5hWgtiLU=,tag:yjRJftXiXvXxHJDXN1vxzA==,type:str]
  PIHOLE_API_KEY: ENC[AES256_GCM,data:+zXFs/DwlDMyjjW122ZtkQhQF3OK+2ycU59F06sjqdZ7XyLeA4GoWzPEIW1dS/7PzruLLHUX+E/VTCzp7KeboQ==,iv:wMgMcMVXb8VfA90rFN/nG0wFSGt3meXZ5fvmVGdj/Pw=,tag:2i+EWaMYG98TWlU80yH2ng==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VDFwMGFrUGEzQWJsM0h0
        eWFYaEREZHBCckhoTUg4NkJJUGhpSU0ycHhnClNpTHEra2pqQVI3TVNoUjN5dTN3
        enRYc2ZGcG1ETU5rMng3bk1RVHl2RDQKLS0tIGVzR2NSQ0JaWnNnYjBxS2FVQzdo
        UWNvRnk1dHdNZERGb0ZjbHJhcXRsVlkKAI6d3m1K8WSBEttht9km8+KgDylvSJgk
        kIONQR4qQ2WgbVHutX1iUkmVS+hXJruiwuAHqmjuekLogoM203NNJg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-21T11:27:59Z"
  mac: ENC[AES256_GCM,data:0NYG4rbvfozlrcm2UPxFOehpnaOQXM3iPAc/ZS5Scfe4/lwXfaxNXIx55Lp9ewdiZlPVFBxFQ+mYV37vL5PdymsIcLVaCwGZIOZrr/qzhPUwQ+aw2Dy+MXU73OaBYg5oy7zd3ho4Qw38wLo38CKIe2BJ58Z/RGTVVU+d+5R5t50=,iv:hZcFzl5BxYAhElG5fhqGE/j4iklxl9+uTJCCOyznZEo=,tag:ynETkYoTORfWG/8+24gRyA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
