apiVersion: v1
kind: Secret
metadata:
  name: crucix-apis
  namespace: observability
stringData:
  FRED_API_KEY: ENC[AES256_GCM,data:pF11wUAK4riZuuhuPmBMGe1UCD2Yw3NAhtTuyIrEIb8=,iv:DrB3oR04lw2TmUbrlL5uDKSueDrFVZrh6a+lRrcEwaQ=,tag:u8p52/zKMXX+0PjTamadqA==,type:str]
  FIRMS_MAP_KEY: ENC[AES256_GCM,data:CfoURrOBN8TITGUmNQlQgo2+ohjiaeBpcAYHju4FkxE=,iv:FHGHQQFALLLZ1jpbLQnhNl2uOX7jzgtQPPKLVHA+eWw=,tag:O//beJ/RZ7X+hImmJiesHg==,type:str]
  EIA_API_KEY: ENC[AES256_GCM,data:gPVMjBAzv0mTbFnRU8SYUWcA5QLXTzEKNSpjbJ9GkdCFm3s1Yxy28w==,iv:F9uhVZ/6x3TLcNSTq+YjzVkmjeffbbYcbNsBLT8C/dQ=,tag:fHQBYSX4vSbtatQAvSxcwQ==,type:str]
  AISSTREAM_API_KEY: ENC[AES256_GCM,data:5pgTH/tnZt3NsECsFJYB1A3CQuM9s4sm0FXFAz2ZvTRtVfnb+RbaAg==,iv:PTlSjzWER0+0a9eKeTF819jbLNnxx3y1FzxxycWYDG4=,tag:AVz1nMxMOXEvCSllxuMFwA==,type:str]
  ACLED_EMAIL: ENC[AES256_GCM,data:IioSL+lBvBKAR+Ghx3SZ3rPigGP0Ezt6RiESLpyl,iv:mz8tKFEPwJn43nkGW8x54+gyMjHv9EL04SGQrgps+9g=,tag:IBZZmgLHIYxzvuKoEUBLtg==,type:str]
  ACLED_PASSWORD: ENC[AES256_GCM,data:CQ9oOpkZI/dp3u3/cyub,iv:wnnLXtKYN8oXLDHIRFJ7T80Jib1w/Y0syc5HngHRL1Q=,tag:99q2kFBE1UV676Cyai18QQ==,type:str]
  DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:QWtdB8oICEEl7eMuOPKkFTgC34mnCOM/h95USGvhnADM6IX3xlyLmMyydi1ANkrmr+Iowr1Sp3ZwLD6IOZck2HALnpqqeaVt,iv:i2POcSzb/ldIhFccTpEPOScrysskSJQZUSmHeEK28qc=,tag:2ekq49nDwZv+75wEMd1clA==,type:str]
  DISCORD_CHANNEL_ID: ENC[AES256_GCM,data:RzPF3wHb3zEsZMP0qgd4i0YxHA==,iv:F/xLoZv0xLisfn2CMyfVLEwCJVLMRXTtxbuwiXJHz7w=,tag:ihpWbNyiMuyvjrPYCYgZig==,type:str]
  DISCORD_GUILD_ID: ENC[AES256_GCM,data:Xou5wmrCRJSeru4YWTXai7vxNg==,iv:N0zqnB1fwqz1+fEOmgzUPIm9P1LWan82FSLmJpsf/gI=,tag:2dxMSndnG6ppMTno/p3ClA==,type:str]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6T1NqYXRJaVo0UFJ6dUF6
        ZFY0cHNqSlF3Mk9JNGIyUmJuVUdpSFowY2hFCjl3ZVJSZ3JNZVA0RmxjaHVlSFh0
        OXRoTzVmV3p3VWpzeG96QmtvSlhjTlEKLS0tIC9PRFhoUnNzdElGVjdIMDlpZGlO
        b2ZiWmc2M3h1eUlyV29hSHVHeFJPZG8KQqK3o/BujZXfjnSDf/+FeotWbAYUWEfJ
        kO3eg6eoyVxmOqjPvQmXkhLDfBKaVrikDfyrZFW3sAkupoDLAk/n+A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-21T20:28:50Z"
  mac: ENC[AES256_GCM,data:DXe4cFAyDWh317LrX50ezHOhZ2nOH7VyLiREJutIuPVDcihPrtfujZbdQfz/j4lTIxQosBXINZ3VqdmxzM8NPajrH2hau9m6ELlVqGdDdnrteaSeDej2ZPtUNJ4s507Rwprq+Q4QSOJqNqS8nXgGWBD2C56GoBWAjsRsS/Es6II=,iv:/6GjLLWZ9WYkJbwTLq5YLmF+99sw8jAuirvY1lmvmKQ=,tag:dL7jAi5iTuddKvTGNmtHsA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
