apiVersion: v1
kind: Secret
metadata:
  name: crucix-apis
  namespace: observability
stringData:
  FRED_API_KEY: ENC[AES256_GCM,data:pF11wUAK4riZuuhuPmBMGe1UCD2Yw3NAhtTuyIrEIb8=,iv:DrB3oR04lw2TmUbrlL5uDKSueDrFVZrh6a+lRrcEwaQ=,tag:u8p52/zKMXX+0PjTamadqA==,type:str]
  FIRMS_MAP_KEY: ENC[AES256_GCM,data:CfoURrOBN8TITGUmNQlQgo2+ohjiaeBpcAYHju4FkxE=,iv:FHGHQQFALLLZ1jpbLQnhNl2uOX7jzgtQPPKLVHA+eWw=,tag:O//beJ/RZ7X+hImmJiesHg==,type:str]
  EIA_API_KEY: ENC[AES256_GCM,data:gPVMjBAzv0mTbFnRU8SYUWcA5QLXTzEKNSpjbJ9GkdCFm3s1Yxy28w==,iv:F9uhVZ/6x3TLcNSTq+YjzVkmjeffbbYcbNsBLT8C/dQ=,tag:fHQBYSX4vSbtatQAvSxcwQ==,type:str]
  AISSTREAM_API_KEY: ENC[AES256_GCM,data:5pgTH/tnZt3NsECsFJYB1A3CQuM9s4sm0FXFAz2ZvTRtVfnb+RbaAg==,iv:PTlSjzWER0+0a9eKeTF819jbLNnxx3y1FzxxycWYDG4=,tag:AVz1nMxMOXEvCSllxuMFwA==,type:str]
  ACLED_EMAIL: ENC[AES256_GCM,data:IioSL+lBvBKAR+Ghx3SZ3rPigGP0Ezt6RiESLpyl,iv:mz8tKFEPwJn43nkGW8x54+gyMjHv9EL04SGQrgps+9g=,tag:IBZZmgLHIYxzvuKoEUBLtg==,type:str]
  ACLED_PASSWORD: ENC[AES256_GCM,data:CQ9oOpkZI/dp3u3/cyub,iv:wnnLXtKYN8oXLDHIRFJ7T80Jib1w/Y0syc5HngHRL1Q=,tag:99q2kFBE1UV676Cyai18QQ==,type:str]
  DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:QWtdB8oICEEl7eMuOPKkFTgC34mnCOM/h95USGvhnADM6IX3xlyLmMyydi1ANkrmr+Iowr1Sp3ZwLD6IOZck2HALnpqqeaVt,iv:i2POcSzb/ldIhFccTpEPOScrysskSJQZUSmHeEK28qc=,tag:2ekq49nDwZv+75wEMd1clA==,type:str]
  DISCORD_CHANNEL_ID: ENC[AES256_GCM,data:+iAZscEQiExKwfRWEJOYZEUmSA==,iv:P5TIF8JgGGccmOrXIXMISdVvk78ft98aYjiBY9AepHo=,tag:9lkawga3i7NZPgrjvjWqew==,type:int]
  DISCORD_GUILD_ID: ENC[AES256_GCM,data:rkU2cK5JQ56IL+35CVpBc8IqXA==,iv:0NQEXuVJNzHykVJlp7WHs2Xep5fK53DGb8J1fbxsN88=,tag:yBNcNSFUIO0VJjjz4nRBbw==,type:int]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6T1NqYXRJaVo0UFJ6dUF6
        ZFY0cHNqSlF3Mk9JNGIyUmJuVUdpSFowY2hFCjl3ZVJSZ3JNZVA0RmxjaHVlSFh0
        OXRoTzVmV3p3VWpzeG96QmtvSlhjTlEKLS0tIC9PRFhoUnNzdElGVjdIMDlpZGlO
        b2ZiWmc2M3h1eUlyV29hSHVHeFJPZG8KQqK3o/BujZXfjnSDf/+FeotWbAYUWEfJ
        kO3eg6eoyVxmOqjPvQmXkhLDfBKaVrikDfyrZFW3sAkupoDLAk/n+A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-21T20:22:36Z"
  mac: ENC[AES256_GCM,data:Kb8CcZeeIC255HE4/sIgFLPlj2KeAnuiV0ras4f6LcmhpkxXHv6iPjPGZGl3iGys0xpp/HSxxFAfPp3+RWZa+9YwhqWv0Yi1PJezlH2IuBUdJXibCoQ8qjG3qE8dEXVz4rPifvdOdlQfN5HYOcAbQtYVerp8OJs4xcsBP9JUPic=,iv:PAh4otQJCHj2XvNx/uPpkAYllEh9dObu54o3FswDrx8=,tag:EIrhmuAJz6NHY+ll2KEWFw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
