---
# Source: crucix/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: &app crucix
  namespace: observability
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 3117
      targetPort: web
  selector:
    app: crucix
