apiVersion: v1
kind: Secret
metadata:
  name: linkwarden-secret
  namespace: selfhosted
stringData:
  POSTGRES_USERNAME: ENC[AES256_GCM,data:RWzm,iv:cPig4+d09VR2xqo+0O3oJ7YH5mM1RqDYvi+Fw1b7HjU=,tag:cK0EyZZcwFWE28yUou3VTA==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:0gNsa1050CB+bA==,iv:inKV6P8maOPSjdWpZOta930mBn1AcgpR5MaAG8xQ33I=,tag:mJqLpaWV5/HFgYQLYy4Ynw==,type:str]
  POSTGRES_HOST: ENC[AES256_GCM,data:ngD4vKk2yvDbqQoypK5VMwXQXzoyYovdg5sAvPoPSVokehbNFt+Oo1RyZy6K,iv:ibSu9shChON1ZsILOKlYNgU1gGbi1Q2jmw/VRmL8ImQ=,tag:jToU5PWDEg2U+cTVpmHXRw==,type:str]
  POSTGRES_PORT: ENC[AES256_GCM,data:AHrkwpb3c9U=,iv:AjT8vTIzsDTPAwYZqyUjU2Ge2U8mlaMeLCPQQSUlzQs=,tag:DXGfA37M8P4vpkF0mBMpMg==,type:str]
  POSTGRES_DATABASE: ENC[AES256_GCM,data:nUis,iv:aadEax3bIX/tBumb7WKex3+gYc2ErUow0zAGqaoNUBg=,tag:M0QdvPS+6FDZmJOdbxiN5Q==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:lpZqv/Q07dj9sR+npatoQwyWgKUZo4ln+a68nOo0KFgDdEYSsikWXJgO6aYjOzktGkGj/BOLIcbxQ4np4+bWo1C17sT1vce2H8RYWbFWmMec3A==,iv:TVHH6qdjAulIObHz/MzTa2korDr01ZVSHgCvE+dQGwI=,tag:LPsJ2APMpOYgDnW4XbYUQg==,type:str]
  NEXTAUTH_SECRET: ENC[AES256_GCM,data:tg0wq+M1BefA2Dm0pd5E,iv:bwCrHwhfVPcY1ruf/yDqm+w7fwzK3zZ4POUh4+o5Kmc=,tag:3GU/Nttw3jFtGvLNEKWtrw==,type:str]
  ACCESS_KEY_ID: ENC[AES256_GCM,data:Y7kL8Iy0AV2zzLfBS+CN0BzDCoQ=,iv:wxH6OrHUuq3xn6Jq8sfVRM4uQRh0YMah+EiyT/vSBDs=,tag:6IEFhDHqXzAzz6dHUBdtuA==,type:str]
  SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ncQiB3S+L/Ny+0ategFNLasyo5BZkHTwj6E2arSgX7RkUqjFpCpFGw==,iv:nxARPDnAmMzkJ3AFiWdIlDlAK8UXK3z4EYbFEte6C48=,tag:nul9yHRYsW0UGrUPH46anQ==,type:str]
  NEXTAUTH_URL: ENC[AES256_GCM,data:JOwj3rRw1b7rbIk93aZMRpwCZN60DAiWnQKTwkmqIX/3NtwiKnVDwaOdW1xA,iv:OGElrs4mPAkD7XLlwGRP03ZS81tc6lKAyCYHtSiy/SA=,tag:VGttguZVSmGJ2FtTgw1KNg==,type:str]
  AUTHENTIK_ISSUER: ENC[AES256_GCM,data:LGdXrZsYv46FxBzv+06E52E18ErnXKuFfCZ40gQwVZxMVjBAIVeVqEQsbsst8ZsLtgRdKJoE,iv:4JqcJme2gMYXyd5S39WvfzNwGlwmy+/h9B5uKI8IC28=,tag:CCR5bk5gE4kIhMWI7N+mdw==,type:str]
  AUTHENTIK_CLIENT_ID: ENC[AES256_GCM,data:lc1MpWjQgCT1drkOdy6BHtJxBzzZPHF8Ik4mn2xvsB/DkGQFLfdV7Q==,iv:6ho33Acd974bmK5T6gbUiUJwx/QZjocwLBYSQzNPzZ0=,tag:C0ASTgeC7NBpLN8DBoL2zQ==,type:str]
  AUTHENTIK_CLIENT_SECRET: ENC[AES256_GCM,data:wTiU3o+6mxby7xAhpiCLqGcb2mz3Ovh1fnbkOvb4AK7vH6/Zg1MizOdaCjWAd0tBh4MJ6TT6TuYiEQnLeM4ZhRtx81hCypt/aHhwygcGXHG7N5fLgr8ejfNh+P2tf8ih7KTdZZcFnoBDS8arjwEwO9JrIEOWcWENQiKtp1MTqqY=,iv:nLWWkwTRaL8cN9VKGqLjVq/Xinc24cdDT5YiUo7/gDE=,tag:pZQNJalE8/yVLvRpEeDOUw==,type:str]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdVhqT2xEYU5razdWbmha
        UWVGQit5SHliTjdibkJPYkIwSTNBNUt6bkZZCk4xK2pLcUFNRVltUkQxOHc5MHRx
        cGJqanVQNXFDZTNHUzlOeFNrRWY5UG8KLS0tIFVzdGk4Tlh3M2pvMFZkUUVldFo3
        Ujl4VFM5VHNMRGlnamVRRjV5bTVEVXMKNwmaVoz7Jm9X4Irmtl9Rx1yXYfS+kUGT
        U/hFAimAUXS2if/DASgTqP6B8W6+LnpcRchSX4rVA5HwBdvd9nfc8Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-29T10:56:20Z"
  mac: ENC[AES256_GCM,data:rAj4Z398Z4hpcnHMCr5yjwYaO/PTKZV6VVOCqprdaCNvF/paZefdlbsL4oqr/yi4DE/dbrKKj/aB8Pf77ESqUsA4kw5f9AotaHd1xHwWCPAjCJx5mEj4eGYPEfaTYlTknutOzXQV0gE4zyUjTiZHMgdAFtzzo0a8uFMR5SA4xus=,iv:BqveuEnEBCvgokhONYdTuK4UPGbgZ9lwqclF6gPwlYY=,tag:5SFBL+/1Yq/h+GqRT5U1lA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
