apiVersion: v1
kind: Secret
metadata:
  name: linkwarden-secret
  namespace: selfhosted
stringData:
  POSTGRES_USERNAME: ENC[AES256_GCM,data:ZCCQmryeHj0lzA==,iv:oXU0BuEKI6ABV5unMWqaV9Rga6eYhjJC+yix98du844=,tag:i/JPR2yGg25+AC96RJep6g==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:0gNsa1050CB+bA==,iv:inKV6P8maOPSjdWpZOta930mBn1AcgpR5MaAG8xQ33I=,tag:mJqLpaWV5/HFgYQLYy4Ynw==,type:str]
  POSTGRES_HOST: ENC[AES256_GCM,data:ayOUoi12jcmU+6KPjxKC6epXIkcjvgbcls/O5L0+Mh3OW3PRP8p7zg==,iv:EdgbU0ZEOUjIKVgjwjtZc9ShPdGCW/ZhWrPFUI5VimU=,tag:hEo9HN9LlQgjGi1S7ru0zQ==,type:str]
  POSTGRES_PORT: ENC[AES256_GCM,data:AHrkwpb3c9U=,iv:AjT8vTIzsDTPAwYZqyUjU2Ge2U8mlaMeLCPQQSUlzQs=,tag:DXGfA37M8P4vpkF0mBMpMg==,type:str]
  POSTGRES_DATABASE: ENC[AES256_GCM,data:w4v9dJpw4ow00A==,iv:zLVBXUCPw/1eArdo5tFEXqDRs4NVqpRSYOAwPx0fNDM=,tag:37Q94xEDu7DTQG71g/Y2Ig==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:XuVVACh9IBctfinWVJQIvUB7Vd7d/6MqHR99juXJ3nfz8PMcDUc7gBzD5BhBNTk55ICXWNGXlG/QQ9P0na0eVLXEf5rxgoRhcX9mvXKW5pwEz6fsKcD1LdDvbQ==,iv:jAqtX+5agqbSay4mC7xxBpqLbd7JZ1o+vC1SI5ReU5U=,tag:HtvcRqDTWfYBY4JTnzBVqg==,type:str]
  NEXTAUTH_SECRET: ENC[AES256_GCM,data:tg0wq+M1BefA2Dm0pd5E,iv:bwCrHwhfVPcY1ruf/yDqm+w7fwzK3zZ4POUh4+o5Kmc=,tag:3GU/Nttw3jFtGvLNEKWtrw==,type:str]
  ACCESS_KEY_ID: ENC[AES256_GCM,data:Y7kL8Iy0AV2zzLfBS+CN0BzDCoQ=,iv:wxH6OrHUuq3xn6Jq8sfVRM4uQRh0YMah+EiyT/vSBDs=,tag:6IEFhDHqXzAzz6dHUBdtuA==,type:str]
  SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ncQiB3S+L/Ny+0ategFNLasyo5BZkHTwj6E2arSgX7RkUqjFpCpFGw==,iv:nxARPDnAmMzkJ3AFiWdIlDlAK8UXK3z4EYbFEte6C48=,tag:nul9yHRYsW0UGrUPH46anQ==,type:str]
  NEXTAUTH_URL: ENC[AES256_GCM,data:sSmzQIQ2AK/dKB4TjUXkJuYjZNZhJJU9Ik65tf4xHQXNbla8fzEFLPu0037KiQ==,iv:tXVn6gMjzi0jpKzEK9oj5lBeiyXT1E45VepqHBMbPrw=,tag:yFvgxYt7WdUNceiVYsdIuA==,type:str]
  AUTHENTIK_ISSUER: ENC[AES256_GCM,data:LGdXrZsYv46FxBzv+06E52E18ErnXKuFfCZ40gQwVZxMVjBAIVeVqEQsbsst8ZsLtgRdKJoE,iv:4JqcJme2gMYXyd5S39WvfzNwGlwmy+/h9B5uKI8IC28=,tag:CCR5bk5gE4kIhMWI7N+mdw==,type:str]
  AUTHENTIK_CLIENT_ID: ENC[AES256_GCM,data:lc1MpWjQgCT1drkOdy6BHtJxBzzZPHF8Ik4mn2xvsB/DkGQFLfdV7Q==,iv:6ho33Acd974bmK5T6gbUiUJwx/QZjocwLBYSQzNPzZ0=,tag:C0ASTgeC7NBpLN8DBoL2zQ==,type:str]
  AUTHENTIK_CLIENT_SECRET: ENC[AES256_GCM,data:qOOtNqzCJrtP/QHEn/ZW5Tn/W96g7axGuUli671VvD+WaN0cCbGi2gSEJ88oJKSXofxa4MnHU2RMxmXVJwIo2Qtq0DXMAxug48ClQIGyJsDHhqURjxdEOgYt1mia9gxqhkJ1h7viPcAh7Eg35xvajrKSPCQFpY+tL/D6LnBUBt4=,iv:FO+OXCHnZYBKCdoV0B5oO3GvUw5xKh/c/vv58tkXzzI=,tag:JdU/QIrqWLDQkXZsC483Og==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:dZqk8kkUMpzI7O+ZAsBJ3hkqh+ju9siFnCvdrRsom88DThAoXr9S2A==,iv:ERcAN5Fz4umjE37smFENrwr1hEsNUSQ9JsKevSxlXsQ=,tag:05l0HEcpfrCRop3TurxSbg==,type:str]
  INIT_POSTGRES_PORT: ENC[AES256_GCM,data:ula8XA==,iv:M7CabhhOPTr/ny52pXHGsdno9y/o1mU31jOPVAO4WOs=,tag:12N2jhRvbAyv84+FFujFXw==,type:int]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:DABnObLGFgHAEg==,iv:9A3KO9XOC/VDpgyLfTZGmN8zM87mzCmQGRoJUQp6MOI=,tag:uM97TFJ5NjLYEdDIGQPZqQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:5N8/J1n6Ba9Vdw==,iv:aiSDp1g/fik+OqG1YyCTOU1AL6vi0SatYnjQ1mRYaw4=,tag:rqYSDWJMHs9kas3aMyD7Rg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:GHH/te6byeogBA==,iv:uuvttfms5Xv7T8QgW/a5zco0iU/yK4BNeCZ7z2nWb58=,tag:mhSNY93mY0H+Y9xItc6fDQ==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:UUojx4FeMSU=,iv:dNiCNOf1LqFRpBx75p/DzoHCH4oU0hjqVpgBM390ymg=,tag:ylbA3ERKKox8sOzepsavaA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:guyk8BwGsZ63ouQSGDM=,iv:bC3dXZPm1JHXsVTclQjl/R/0WSoVDO3fCz/3yL2AR6g=,tag:WxfzgbYREAOua+vU/mjl+g==,type:str]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdVhqT2xEYU5razdWbmha
        UWVGQit5SHliTjdibkJPYkIwSTNBNUt6bkZZCk4xK2pLcUFNRVltUkQxOHc5MHRx
        cGJqanVQNXFDZTNHUzlOeFNrRWY5UG8KLS0tIFVzdGk4Tlh3M2pvMFZkUUVldFo3
        Ujl4VFM5VHNMRGlnamVRRjV5bTVEVXMKNwmaVoz7Jm9X4Irmtl9Rx1yXYfS+kUGT
        U/hFAimAUXS2if/DASgTqP6B8W6+LnpcRchSX4rVA5HwBdvd9nfc8Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-29T11:21:33Z"
  mac: ENC[AES256_GCM,data:yODHkS7tqgWjwbvpvdVUvY5i18cCakO3OG7lDVL+REWLvo8GW9fBU4oJmN9whsfsKWZX00Q1Mw3mOq6E0/dpX7jJHKbZzfE9uXNAva5Iq/R9gFtiUhhlnVwO4WA5FuEuTv6Bh9zt+JwFZlNfCm8hlRnJw6XwachuXNsrbdoeveM=,iv:U7vRHqXsY6YutzoHdLqnq1fbPEcucOeKQF+fUGuh2vs=,tag:6heNYcBjgnlEf6WuHLI10A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
