apiVersion: v1
kind: Secret
metadata:
  name: loki-minio-root
  namespace: observability
stringData:
  rootUser: ENC[AES256_GCM,data:0+aY7RQ=,iv:PcD8emdnzrCnkLI4axsEiwN/aE7AcPrGA2DFpaiSbYY=,tag:gOhVm8DNbhZFkKgROZ31mw==,type:str]
  rootPassword: ENC[AES256_GCM,data:nqnnmes7ehSbKZqFXlzzxNs=,iv:Ji/BtXm/1wkYS+8VQ5z3T1bmqTFKmnOUNt/RvYslaZs=,tag:zFAxZ561u2geGNrFoEIQ6w==,type:str]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSXlBRUZCK0NHMnd6ZkF0
        bi9ydTdENnE3a014SXZvRTVnWWJ6ektQN0ZjCk9NNDErQUljNHdkeWlBSHJxK1k1
        T1dqNzlpaGF6a3FTdERCT0VJN0hGajgKLS0tIHk2Yk5sN0lYUS9xTXZ1U29EcjlW
        RUZMR2ViTmJGdUc1OWVkM1hka3ZITWMK4kswfM9qLOGmAWPEkiAg13/xi2U4xRcw
        Y5sOwnES4U5GGl4g8Aj+xEiIocnoeI4Y9EVmQakZGg3YbGyCsxXZqg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-21T10:37:17Z"
  mac: ENC[AES256_GCM,data:zmoiYWyJqryf/HC2fKx53DJw5tWKad+wPYI9Q+JjKz8BGS1foVQnqkDMzcFURVzoQGtXzIk9iSTInx+fBxYhb6r5j5JiEzAWTldiRjV4u5c9avr81owZY/mRbrztPU0MlvhVMPTzP442aSxkpanAcx8B8MFHoV7I/0XI7aMyGkQ=,iv:11NQx6X9a2JnQlTEejW7xFPxWF9J/eVsGosmNpioxdM=,tag:PLUQTvQDIZPUBfSGkpkJuQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
