apiVersion: v1
kind: Service
metadata:
  name: avto-masini-web-production
  namespace: avto-masini
spec:
  ports:
    - name: avto-masini-web-production
      port: 80
      targetPort: prod-svc
  selector:
    app: avto-masini-web-production
  type: ClusterIP
