apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole-exporter
  namespace: pihole-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole-exporter
  template:
    metadata:
      labels:
        app: pihole-exporter
    spec:
      containers:
        - name: pihole-exporter
          image: ekofr/pihole-exporter:latest
          ports:
            - containerPort: 9617
          env:
            - name: PIHOLE_HOSTNAME
              value: "10.0.10.200"
            - name: PIHOLE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pihole-api-token
                  key: api_token
            - name: PORT
              value: "9617"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-exporter
  namespace: pihole-system
spec:
  ports:
    - port: 9617
      targetPort: 9617
  selector:
    app: pihole-exporter
