apiVersion: v1
kind: Secret
metadata:
  name: pihole-api-token
  namespace: pihole-system
stringData:
  api_token: ENC[AES256_GCM,data:MTE/bVUTxXhG67gQvZNBx/LGO3VszVSbV/pvAsBL6xv2X53mdZhGu5AEnNnjpqgBxjvOKeHAi4lK2D6tEke9Vw==,iv:7ah4sO2CbnJqbg33vMa7x3Qiymc0PxCOKkWOjMIJs3g=,tag:zjDSwgsTLFPqJZGO9vp8ag==,type:str]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVRlV4RmJ3WmNRQldsWUl6
        VTJkT3phb0ZGSExQV0ZaWTc1RTZ0TENoc0VvCk9CQVNRc1lYK3h2M2F2MkRUWXVG
        VlZpZnQ4UVBBNWxlK3YzSlJBeFFxQ1kKLS0tIFFZQW1rTWIxUUVvZ1NIYlNyTDVo
        MURwNmxXaVJZV0ZVb2RqaUpTZEpIRUEKH6Iq6+azhNsHp7dhTw7uJC1KQZx7H+t7
        lQ1sIhJsZnqR6jwXVrta0KUT5juFvLNB80hGkQqQOSQufjcLsQK4gw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-20T08:12:46Z"
  mac: ENC[AES256_GCM,data:taOomc2nNxIFIgJhnMZORl8boMaMr4QXmIVcEOwNe5ThPTjE6WXKv7UJUxOiAj4evsuAp5T/pCoOCECA61iCM4dL/MDIJu/1HOspLSWLSM3xeaSp/93aUbejqTSNyrAqJMKBXW31t2O7G5IBk++EFZjnoxcxUO/KcDC1sk3EzKk=,iv:p5NrxgHRIXrQS8BAFJWH1txQXrskB8aYog7XlxTqpQ8=,tag:gfCA80rPHiozg514nlH0Tg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
