---
originRequest:
  noTLSVerify: true

ingress:
  - hostname: "dnsk.xyz"
    service: https://ingress-nginx-external-controller.ingress-nginx.svc.cluster.local:443
  - hostname: "*.dnsk.xyz"
    service: https://ingress-nginx-external-controller.ingress-nginx.svc.cluster.local:443
