---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app paperless-ngx
  namespace: paperless-ngx
spec:
  interval: 30m
  chart:
    spec:
      chart: paperless-ngx
      version: 0.24.1
      sourceRef:
        kind: HelmRepository
        name: paperless-ngx
        namespace: paperless-ngx
  # install:
  #   crds: CreateReplace
  #   remediation:
  #     retries: 3
  # upgrade:
  #   cleanupOnFail: true
  #   crds: CreateReplace
  #   remediation:
  #     strategy: rollback
  #     retries: 3
  values:
    env:
      TZ: Europe/Berlin
      PAPERLESS_ADMIN_USER: "${PAPERLESS_ADMIN_USER}"
      PAPERLESS_ADMIN_PASSWORD: "${PAPERLESS_ADMIN_PASSWORD}"
      PAPERLESS_URL: "https://docs.${SECRET_EXTERNAL_DOMAIN}"
      PAPERLESS_DBHOST: paperless-ngx-postgresql.paperless-ngx.svc.cluster.local
      PAPERLESS_DBENGINE: postgresql
      PAPERLESS_DBNAME: "${PAPERLESS_POSTGRES_DATABASE}"
      PAPERLESS_DBUSER: "${PAPERLESS_POSTGRES_USER}"
      PAPERLESS_DBPASS: "${PAPERLESS_POSTGRES_PASSWORD}"
    postgresql:
      enabled: true
      auth:
        postgresPassword: "${PAPERLESS_POSTGRES_PASSWORD}"
        password: "${PAPERLESS_POSTGRES_PASSWORD}"
      primary:
        persistence:
          size: 4Gi
          storageClass: longhorn
    persistence:
      # data:
      #   enabled: false
      #   retain: true
      #   mountPath: /usr/src/paperless/data
      #   storageClass: "longhorn"
      #   accessMode: ReadWriteOnce
      #   size: 1Gi
      media:
        enabled: false
        retain: true
        mountPath: /usr/src/paperless/media
        storageClass: "longhorn"
        accessMode: ReadWriteOnce
        size: 4Gi
      export:
        enabled: true
        retain: true
        mountPath: /usr/src/paperless/export
        storageClass: "longhorn"
        accessMode: ReadWriteOnce
        size: 1Gi
      consume:
        enabled: true
        retain: true
        mountPath: /usr/src/paperless/consume
        storageClass: "longhorn"
        accessMode: ReadWriteOnce
        size: 4Gi
    ingress:
      main:
        enabled: enabled
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: 64m
          external-dns.alpha.kubernetes.io/target: "docs.${SECRET_EXTERNAL_DOMAIN}"
        ingressClassName: external
        hosts:
          - host: "docs.${SECRET_EXTERNAL_DOMAIN}"
            paths:
              - path: /
