---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app paperless-ngx
  namespace: paperless-ngx
spec:
  interval: 30m
  chart:
    spec:
      chart: paperless-ngx
      version: 0.24.1
      sourceRef:
        kind: HelmRepository
        name: paperless-ngx
        namespace: paperless-ngx
  # install:
  #   crds: CreateReplace
  #   remediation:
  #     retries: 3
  # upgrade:
  #   cleanupOnFail: true
  #   crds: CreateReplace
  #   remediation:
  #     strategy: rollback
  #     retries: 3
  values:
    env:
      TZ: "${TZ}"
    postgresql:
      enabled: false
      auth:
        database: "${POSTGRES_DATABASE}"
        username: "${POSTGRES_USERNAME}"
        password: "${POSTGRES_PASSWORD}"
      primary:
        persistence:
          enabled: false
    persistence:
      # data:
      #   enabled: false
      #   retain: true
      #   mountPath: /usr/src/paperless/data
      #   storageClass: "longhorn"
      #   accessMode: ReadWriteOnce
      #   size: 1Gi
      media:
        enabled: false
        retain: true
        mountPath: /usr/src/paperless/media
        storageClass: "longhorn"
        accessMode: ReadWriteOnce
        size: 4Gi
      export:
        enabled: true
        retain: true
        mountPath: /usr/src/paperless/export
        storageClass: "longhorn"
        accessMode: ReadWriteOnce
        size: 1Gi
      consume:
        enabled: true
        retain: true
        mountPath: /usr/src/paperless/consume
        storageClass: "longhorn"
        accessMode: ReadWriteOnce
        size: 4Gi