---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: paperless-ngx
  namespace: paperless-ngx
spec:
  type: oci
  interval: 1h
  url: oci://ghcr.io/gabe565/charts/paperless-ngx
