apiVersion: v1
kind: Secret
metadata:
  name: paperless-ngx-secret
  namespace: paperless-ngx
stringData:
  POSTGRES_DATABASE: ENC[AES256_GCM,data:a1wyb0cFjj99mqWb,iv:huFoVP5xDy70rgccF8oICcBR1NAuU6e8uvpyT1BgBk4=,tag:iODoKwowQDn5HL4YdnOMuw==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:wXjD1VHGUcA31A4dd1RENfen,iv:H3u7HRO75kJCndGwk6pd5E2f/b5buTCm25IRYh922lc=,tag:iYeL6t4LgqL3QBoM1wWNMw==,type:str]
  POSTGRES_USERNAME: ENC[AES256_GCM,data:73xvsRJqH6sU,iv:v6a5MdwwNzH6E/6sBa1YHhtVy/fpY9k9r5M7Or2BtsY=,tag:UL1o8cdiZ5V//BHqMQlNHA==,type:str]
  username: ENC[AES256_GCM,data:ez610nippRTn,iv:sf16DOHHKCC3jYBPYXOarMKob46mul6SqgqzVk4d908=,tag:zAoXfwalnds8yofIfgPHvw==,type:str]
  password: ENC[AES256_GCM,data:HYpkWgD2Zv7+Y8XJwwQnPpqB,iv:vm7OJkBr4RFwFFNb35sWPfmKWbIZTa3tJaFehxMASoE=,tag:XEtnryGihrYHAwVPWy+eBQ==,type:str]
  tz: ENC[AES256_GCM,data:X28hHcDqb22zSZVTCbSqqA==,iv:LCJK/JGz2HUU+0qus6qODsi6G606nJGryp018xiB93A=,tag:H/GIs3vlouWOA57Zbc56dQ==,type:str]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUDFNL3lrYXVkbFBPZ29h
        eGt1WW9Ia0JSSGQ5NXoxcGhpdGVpd3Vld0FRCmVqbC9pclJGK3hCV1V1aXlicnlz
        c1hWR1B5YWUzcFdFRnRkSUlLYWUvREEKLS0tIGJ0ai83eTZtejlsdDNkNnp3amlM
        cUJ2Y2MvOEZuY29qZnZHcStpYkxoQWsKdmivQRw5D6C3MO+ZHIMh3h0NYO/4tvLB
        lZCUkkJcRwgRhbxleQSYLghiPaYld/2suj7l/bbZ6p6s9o5wKkEhEw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-27T14:44:52Z"
  mac: ENC[AES256_GCM,data:OVCHXiulSdFeSwxdnfhWGxns698EDFnJmLNcc+sjcYcUi+tJTx4MxIpPboix2xjqZ07XvfgbWatqJceUnG5PNH6HPrzxzagfOeX2oYvBszr9Lu8I6FSCeCMBDCzcH9ld3VNakUHVWMTnt2+AjjaWrhqBdPr3HQ8QafaytdvhkQE=,iv:lXA5un3D2E+lWnSG76JRowHkGuHl+Ne+h9so/YK4vxs=,tag:cOrymiuMlUM6VwE6wYh+0A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
