apiVersion: v1
kind: Secret
metadata:
  name: influxdb-scraper-credentials
  namespace: goriva-si
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:h7bs7VjcNYuzr+tjuvAlN9A2jfTj7JnIQGeH8UDkBddV+XmsKCDEU8lhKyG4KsQMAmUeWIirUFFPQ68Z8A==,iv:RZenm9HlRBLcrKs/dIW21EBjSf4O7nlQWjsiU8OrkGo=,tag:V+V2jQZCw4xY2sE+ltTS+g==,type:str]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDVktSMVNSQ08rY0ZUU3Na
        MmdJczY2WS81a2ljZzZhWW9GU0lZeExyZmxJCmVCcVlmWWoyTEdEWU1JZ2N4c0Ni
        WlZRRU1HMnVzRXVsK0Jhc1ArVDJRR00KLS0tIGZ1Y2pJM0VsdVRRZGFnTWNOaHJi
        QkQ1dU4vajh2OHdKTTBnRWVZbXo5dW8KIvi3mWEV2A+debNc5tp9X/r8wQCKZuah
        aXc5T08j/tWtZGLQnTN3f58235dvzHyiVDaDzERMc2jWmNCPF/pCzw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-26T20:02:56Z"
  mac: ENC[AES256_GCM,data:mYVx6ytBwNo+vb+bzA3ujmW/vV/kC2uNHbnPBDdnTboXJW2u9fDrpxcpw4TZqlMy7pqVs+u4lNFiXPtfHaTd+eZAqURKzupHsh7czJ5CZRnqA4fYi94WZG42NbutLTZNT+G7SEYqqV3QUg+V3r4HUDF8sdP5qKDZRJCd/L/OrvE=,iv:mmOPiqdBsyDQB3QlYBsW3IVOGKOmKAPEIrvetuXOTRY=,tag:Lx19Uq/96SoXxLp8z3I9kg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
