apiVersion: v1
kind: Secret
metadata:
  name: influxdb-admin-credentials
  namespace: goriva-si
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:abqbOlACcy+DDS5PJPmLIQCK8bLwAHEa3xD/JibQ/nwvHrgqOsOfMuoBo1UNxAw2eq0lobZEQlGlgs+uwkDcSg==,iv:ejiN23Wn3h+bWBeF4+kghpGrK0YseZIzHEy4KUdwBvE=,tag:4CGl12SXgYK3iUZk7jYSYQ==,type:str]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIL3NaMlpCUWpQUGUzMEhV
        bzQzSlpRak15QW9LRGVJVnk5eDFWR3ZISlFjClBmT2JZc2gwV3lyZktya3RBQjdk
        VHNqRnprVHJ2TFJRMzFvOTIxK21PWTAKLS0tIFhCekQ5WTF5bHQ3M0o1eU84OVMw
        QVNuUm9oZ2JFM0JvVlRKb2lDV21DdmMKrRkLmMkjNIvAAL3bSZxgiiexfCjwWnLl
        x4al5cmMQW29ME3yT/lpjcvH9ENK9So29lo5jnF5whqYRfYPlXFcfQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-26T19:07:16Z"
  mac: ENC[AES256_GCM,data:SCiXQhFSUo6KWGVWAWb6MxOKIBMgiQ7vnAKxRVRaNa3I7gjrfIo1z6x/O3UAeFn2YSjTOnyPbo4DLBsIAmba+Bx3IpyE0jpRGNcHWbqSN7M3GnTwNZ8Upi/uVR4Dadg/+otSzjdUy68ijb6m9JDjXlT6zl1ArbOEQ/iR/u8/6V0=,iv:UJpVTBPYw8TtmAFn+EVlcfteNMC8nFStPhkfA0lsbFE=,tag:+5uzbF8wMklxvI36UQIsTQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
