---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vault
  namespace: vault
spec:
  path: ./kubernetes/main/apps/infrastructure/vault
  prune: true
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
