apiVersion: v1
kind: Secret
metadata:
  name: kestra-s3-creds
  namespace: kestra
stringData:
  s3.yml: ENC[AES256_GCM,data:n0eHL6TsAFMrjJXK2yCDq9YWvTxnRzKO4VT4PkdziZRWKt0b0Ol+mxox1JpzykNpKb41wkimGa+0rmyCg9TWHumvOBYTgunZN26RaDxDfbBDg1kdUFrg4dj9nwTSNJGMzpvBmiqa3FFKs2QOXeav//K7K+Lq8/IljT9VSkndOFNBw+EijqEuzOaulfT63HXVMyNlLxbq1j1o9q3MJE6wg3ea5VCe1eqvF023YHxvQOxRBMpP2U6/Yl7bQfAcllmm1Q==,iv:6MJUJp9PKuxLQRA7XoA9nroPr5Gvqa1DiUeIjjDWDc8=,tag:dVzJgKi0d23G5+/DP1sSdA==,type:str]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZmlkNk5PZTZuVTZSTUpO
        ODBoU2dzck5tdHRSRWFBdkhYV3FiY3RmaUFFCmd0M1hMenEyQU5PN0I4TlpMRUNo
        UVZtWDdxaHI4T0V5Z3ZSWUhWVmt0bVkKLS0tIHlGTVlNUlNrcHZnSm91WDZHMXQ4
        R2dyd2lWU05VSFR1ZkZROVhCRlpNak0KQZQSz1U/zBVexWakRiJt8h0RE8x1ODOm
        YwBe5sfYA2cbeUFXBODzyTI8W11ONjTQm1n21Lq65bsy0F6RE+y4bw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T19:44:42Z"
  mac: ENC[AES256_GCM,data:LQkIb7g9IAubPaAAY07SYfqweBea4uotoQqUrPkHguOXUBwrEICCrGOcCmoj5gvVIIyItqHRG1hKqf9AzvOiWAxH0EDgAveNN9aIR2ONpDreCUSCZCQDI2JTYC9U0ygxFaBfsH/IzW3bVSePt5shXHP2sBH8TMoe3E769fUtQXA=,iv:2eLuh3JmVEAyOiMNg4Q/YTuueRfrAi/4Iw1RVlgpy7Q=,tag:KylE1Mb/S1jZoVg3EvMN/A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
