apiVersion: v1
kind: Secret
metadata:
  name: db-creds
  namespace: kestra
stringData:
  db.yml: ENC[AES256_GCM,data:dv2JSFstCXvTWRPnDnrlH4IBMmKeOQ2iQkw7Wdc9knCGrsSslTvYQ/sPer2+ur5Qb4rFJ82DhVuvF0MIqlU2auOnfPZlAkkHfWtDGZB5XaL93iy7y9njbwZNDUkvuHu/gA1sjIAsH6SlREta7hIS5AutBawZ7XqwccqC5mJlFriHlNlBoA9vHADma7KVSt5BuD2wli3LAWrrbnNMQXDzt2uq3cBbHqPHbzfCNhJIEW3+xS8c5UW90euSoGFZH+5svYzX,iv:ZcGWv8qssQdpaxtpbV0uslvMVajrAx8ZuKK0wIxd5Gk=,tag:pXY+tK/YSB1vC0leru4rQQ==,type:str]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbVFiV2V5K3U5UkNQV09N
        QzBTc1lLdlZIS2hsVlJINi96R0NGVWNISGpRClA0bjhJREpuTlpjcVFyaUZKd2J1
        RzdOVTJoNE1peVEwM09QcWJIdnc4ODgKLS0tIGk3N1lDTzBQTzNFa2hCaGE4a0lB
        YkRVOGcyM2tSZm54NWN1RXZ6LytSNGMKPHfR6roPQIWCaMuqm5LsFemTkLI1ZQ3i
        IMb/bLOEo3I4/wig2l3NZ0M374KzEVP5oKgM7vKCL9/GpoUaTztFWw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-13T10:21:55Z"
  mac: ENC[AES256_GCM,data:nHusho3R97rUsiIqK9gGnNWYF5NL1p/FTt1mbPnosCrpLd6Ge1wIsi0MPmPZ5JbZOBdGnhLPhoAJBnjq9XfM3P+ErCjQ9ukC3bJ7VAjKzi3w5/jBNzlLiFMGnl5olATXm7zcCjeXeIN7DpGlNlV1IRzPcrJqeo9h4Y06b8J1Z3A=,iv:eTdjdkB5knnQaK+PBy6Ut3HVJV8z8KZ45R6PDabCJmM=,tag:mVJku4HefzNSWURNWj5c9A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
