apiVersion: v1
kind: Secret
metadata:
  name: db-creds
stringData:
  db.yml: ENC[AES256_GCM,data:NqDY1ZRnO0J5epSzKkKyfkPyFFUfS0ZlJGFfvzSvG1RPLmXBO7B4G2RUhVh/7GrLoV9GFkOSVuV2t+J4soHa95M9hKLpNwLtwz0jTjiDtitckmHhSDE54n4wUOGGgKugSP8f8XjdLgINuMb2GuH3/k+skSEE+MWfV2rA8UC8U6fzDYH7LBVQ9h9HW4Fy/kVv1KfRWCbfPEpIrwVhjwMEt/u0r6pdli4mrQ==,iv:wA8JdZ0mF4nwDKAVu6RNT4DJ1e21xHuvao72NE+gd3o=,tag:Xy5p2zLWRzniSsxbpVAl7Q==,type:str]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbVFiV2V5K3U5UkNQV09N
        QzBTc1lLdlZIS2hsVlJINi96R0NGVWNISGpRClA0bjhJREpuTlpjcVFyaUZKd2J1
        RzdOVTJoNE1peVEwM09QcWJIdnc4ODgKLS0tIGk3N1lDTzBQTzNFa2hCaGE4a0lB
        YkRVOGcyM2tSZm54NWN1RXZ6LytSNGMKPHfR6roPQIWCaMuqm5LsFemTkLI1ZQ3i
        IMb/bLOEo3I4/wig2l3NZ0M374KzEVP5oKgM7vKCL9/GpoUaTztFWw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T19:50:47Z"
  mac: ENC[AES256_GCM,data:+9TqmOnniGq4L7QkD+123s5oDMb4re+Lv34ACSgjIeYT8vZUVYkJqgnf7WHesrMnqxi37PbtghWaAdDbhI4ChukTxRKMTpC//cKcEXH3wFzC0sCaCrin26dY2RJ+Mn70P/ItrAKDru6qDXqKVyxM9DgO1rSoVPb95vJTXMJDXfU=,iv:dUHk3m64znRAP6Puih6VySP6MFfwN3q+mWCNbVMfNuA=,tag:Kx6wxl7+wSs89C/L4a+eIg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
