apiVersion: v1
kind: Secret
metadata:
  name: db-creds
stringData:
  db.yml: ENC[AES256_GCM,data:qz3LmSCOm3CEVnFVGXkt/k9MEjOrEW1ULbmBmoyVkRbeBtTAUS0CBy1JdPJz4+fXg8iU9Poiu/rMHCsk+ryyxQf9AHPrCaaV7/03YYO3ardA0df3t5MVfXEU0rqHBWxnU0FgG8nyS41OomWAhd8Ct0r0hOzO9AqBxhXg4TYuxeC+G2y/UPy5ki0v6F4su9GRrHxvOFh9H0oMrPQVN5JUCepsrLqBa+w5,iv:+cVnEeXLeuD28Yg1rPEEn7hPmRTBNWji9VQ2MiNQx/4=,tag:+aIt+iBIfIW5Tupgl9mT+g==,type:str]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbVFiV2V5K3U5UkNQV09N
        QzBTc1lLdlZIS2hsVlJINi96R0NGVWNISGpRClA0bjhJREpuTlpjcVFyaUZKd2J1
        RzdOVTJoNE1peVEwM09QcWJIdnc4ODgKLS0tIGk3N1lDTzBQTzNFa2hCaGE4a0lB
        YkRVOGcyM2tSZm54NWN1RXZ6LytSNGMKPHfR6roPQIWCaMuqm5LsFemTkLI1ZQ3i
        IMb/bLOEo3I4/wig2l3NZ0M374KzEVP5oKgM7vKCL9/GpoUaTztFWw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T19:58:34Z"
  mac: ENC[AES256_GCM,data:WjX3aabHB6rgv4Lu1wn11pb1S5HUmnLNzO+aDCczLQWgCUj+HiqpAjeiR6gPvuYHfPVvD1qQalOr8l72JGMSgL/aRWRqdJJzvX5Dm7wgSPn16Gtz9Vu4MM7b3vA3RvBcaPM7crxlF/TyxSlBeB7wnhSUqY5gvtvOiifjG2GaQXw=,iv:k8p3UfEvjmh+NPoU9/QtW4my+WCEs2/Pp3M8z1jl//c=,tag:dZ8QmvJ3CZXiwB4lLV391A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
