apiVersion: v1
kind: Secret
metadata:
  name: kestra-files
  namespace: kestra
stringData:
  application.yml: ENC[AES256_GCM,data:hcSBp/pifw6tBRprmu3F0w3ucBxSZJSfD2nKVSjiEUN+s6DquLlqmzCWf4GCxq5O4Fep7iuAuXiqlTnwgg9aBmSMEDDqSSoqIw7ETmplDdYLtCFgp9Or9l36y22vHArlcXn6oo/wxcNJxTuz0w/Dv9jZXEDeDh4ZlgdpOYQp9HK+avd6UaYkmXueMgaXOPo/F1q69x+OmV6yGRubU2f0fT80gighbuZfECNza7K07QWJudIUZJkfbHZySGf9Lg8ZqhY5jmZe11N57GvUR2hgn/4CHTQ4xLuVJvuo77ivhriZpxUjoiCEi6np6c+vymF287UT2gh2GfVUDO8tdTyWxem1MSH9k/M1J4LrZNfPR40vANbaJV1f9qr+YnBHv9X0no9ERh0KhHZ7HhT9ZWgFP/vIscLd73zyh5NUeeN5wrXLER61PlOS4wakmWWiLsnLYAVc33wFdEL3QnknM4J8zR9XfsAnyh0Rrh6p6uwuiXRzQOmgPzh6raBJjGCAHUGvSJyAOZUwA8mu7gC8n3tQQ8yko6hcldw3KGCdyCKqLmBW+FyEG8hb7nITu1YeljRKibw4LEvE0T4=,iv:WSlkZAp2hpyksGBe52W6m5GoBYYZp3SmZ9uRu5CdXoc=,tag:E2XzkY7wmhHJR/jHq2bFgg==,type:str]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsKzZ5WXNUeXpQcWNFWlJI
        U0hLVG5LVm13NGJkK3A4YWJDd1Mva2JkRVNZCmo1QlZ1TW1zOXRXaERqUjFneHgr
        YlI4QzIyemE1bjJKdFl1aUw1cXZuNDQKLS0tIFpCQlRxdFA3MnUwZnMxLzQ3enZB
        cDMzSGEzNGpQSFVnNVBHejZ5a0dnSzAKtYv7ds2GbDIe6G74j4HvyaXwfokEgMw4
        G1P3OUvcd0MEACTdqVraPR54lReODXt0xvc7SQl65XdB44IQ4B1gaw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T19:31:39Z"
  mac: ENC[AES256_GCM,data:ZUMV5rUdT59pdcqHCjij3b4Gvnz2K/qLikf6WqLj8FlrsG1KcMXDq+vMmcOnyoV2oYSvVpJzAfZnVYHA9lQ2F+m8PnLhFVXKkIgHP8y8vBM5BVL924ealyJVqKiQCGixv4t52dmEa600Zx099708q4Eu4WZmgDlV3AivPgxTxuQ=,iv:cvakuuDc5/DZX6G6MAQ8yXh0dGj1ywIRBEivoiPRXEQ=,tag:QeWRy1lVQfbHVVz4CfToKQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
