---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./repository.yaml
  - ./s3-creds.sops.yaml
  - ./pg-secret.sops.yaml
  - ./kestra-creds.sops.yaml
  - ./kestra-db-creds.sops.yaml
  - ./cluster-pg.yaml
  - ./release.yaml
