apiVersion: v1
kind: Secret
metadata:
  name: pg-cluster-secret
  namespace: kestra
stringData:
  username: ENC[AES256_GCM,data:gcrD1dKi,iv:QaNOEPh7kPM9M0+e+itjBAl8bbemY5IxUJcYC3W+zoI=,tag:7/LAx/tj4z89+spg+gwfFw==,type:str]
  password: ENC[AES256_GCM,data:svq12hdPuEgIrA==,iv:OUH+NKeaeSJn2adFvM4MUB8y4EUu7dHttaMuiDbOun4=,tag:w6Ywsbls08lWAl822SOq9Q==,type:str]
  POSTGRES_USERNAME: ENC[AES256_GCM,data:7DW5uzVc,iv:+S2qMhFd68kiRPLYxLVW123UUkgdVtrdOiVcGg9UVoc=,tag:sH/j4H80rnrz8eHNMznadA==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:/ErZlVixmbccwg==,iv:n2RA49W8R2CcR6Y/DfRnlUo77zI4lhDspkrDZKMeiVs=,tag:cNu6LOCktr43VzyCqBUXzw==,type:str]
  SECRET_DB_USERNAME: ENC[AES256_GCM,data:7tUcLw7t,iv:PBFhk5+Jv4nBgCXhWQVS4OJxKm80MNo2odtjigi3ykI=,tag:ZQIOhKhVkqzwmybjyNfmqA==,type:str]
  SECRET_DB_PASSWORD: ENC[AES256_GCM,data:xaMgyup7GHEmiA==,iv:4ch/0o+g7YqfSM5lnLZCEgm/QcutVYwJpRhZh2SndN0=,tag:ajvm0LFAkocjIn9nCt0/+A==,type:str]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByS3FCVlhZNC9hWDFqRVc4
        UWtnWHltcW92UGVxM3FWUm05V3orMk1VM2pzCmIxaVFndGF5cjlidjBGaXNCQzJj
        anR3Z0tlb0FXQkljdWQxZnJNSXd5RFEKLS0tIHVvQ1ptYVRFL1JvV0FPUXRuRXhB
        QVdycEFBaENMYUdCcDN6TUVuWXljQ0EKD/FObiHq/BcbX6UAZfSeR4wLft4umuCx
        ODaDRBT3iws9zC7Jsm9oEBPWm+cPIbz6NGdcI+Bsbw4K12Ggei08ag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T19:58:17Z"
  mac: ENC[AES256_GCM,data:spEt496GzcPhBkye1IfjGGAb46rYztfXRDjzkci3RWoVe4ppUQ8ZaBelh50EY5oRp0EbJ+UCLAryAqNex9SKpPI7RirG6hnNaVdrz/GvXfAm6Q9W1hc482H1dW5RHWhNfIOyKd9Lison75dN7LDcAn6pVrSmJ2O+jRhPjs6C9Us=,iv:mgrqagBoIv3ekaYRZqGoxk04wXud59gjRG7xQMk0Ta0=,tag:5gCoC9k3ixtSuyj04tfemw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
