apiVersion: v1
kind: Secret
metadata:
  name: pg-cluster-secret
  namespace: kestra
stringData:
  username: ENC[AES256_GCM,data:gcrD1dKi,iv:QaNOEPh7kPM9M0+e+itjBAl8bbemY5IxUJcYC3W+zoI=,tag:7/LAx/tj4z89+spg+gwfFw==,type:str]
  password: ENC[AES256_GCM,data:zZeg4bW3ck9dcoM=,iv:Zli5+Qwv2djehdASXbhYDEx8rBoiWfpeUuzjc8PPkZE=,tag:l/wl3PP4/nrq4/GVOjmkYQ==,type:str]
  POSTGRES_USERNAME: ENC[AES256_GCM,data:7DW5uzVc,iv:+S2qMhFd68kiRPLYxLVW123UUkgdVtrdOiVcGg9UVoc=,tag:sH/j4H80rnrz8eHNMznadA==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:vEajP0U9erc0XQA=,iv:vHNfF8hmpJcYF0cUpBlZ6Qjc54AjU7mgYwNhApwXbhk=,tag:sjncFk6uQAtJJ1mgsJKX3g==,type:str]
  SECRET_DB_USERNAME: ENC[AES256_GCM,data:7tUcLw7t,iv:PBFhk5+Jv4nBgCXhWQVS4OJxKm80MNo2odtjigi3ykI=,tag:ZQIOhKhVkqzwmybjyNfmqA==,type:str]
  SECRET_DB_PASSWORD: ENC[AES256_GCM,data:DAj/r90EsV7Yrr4=,iv:4ScBut25RH9jRVsx/OgFc8T1vK8pV/O7EJBoVmu/Jhg=,tag:kdMTvgQrYVAocRf1w6vksQ==,type:str]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByS3FCVlhZNC9hWDFqRVc4
        UWtnWHltcW92UGVxM3FWUm05V3orMk1VM2pzCmIxaVFndGF5cjlidjBGaXNCQzJj
        anR3Z0tlb0FXQkljdWQxZnJNSXd5RFEKLS0tIHVvQ1ptYVRFL1JvV0FPUXRuRXhB
        QVdycEFBaENMYUdCcDN6TUVuWXljQ0EKD/FObiHq/BcbX6UAZfSeR4wLft4umuCx
        ODaDRBT3iws9zC7Jsm9oEBPWm+cPIbz6NGdcI+Bsbw4K12Ggei08ag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T19:41:38Z"
  mac: ENC[AES256_GCM,data:g1W0BOQRbdv5qOqcUipZDdGBfJA978lkFIX/Qbgmoa9HdCARZ4c/LOriXxAhS/FvPvF3gIabDvjz39Cu/ae2zKUDMAdkMzPxslQrLjnfGIgx9CKXuEU1cjNqYsfSam9N8U/PvkyIs5aF+MikvlCiWLBnKJUDR5Ea0BjWyIMW3xg=,iv:mDvkqVqz09rESTnwnugh+1kSBkfd602kik04pYMjZFg=,tag:Uwua6EYrhBq3YrWfAhsGQw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
