apiVersion: v1
kind: Secret
metadata:
  name: pg-cluster-secret
  namespace: kestra
stringData:
  username: ENC[AES256_GCM,data:gcrD1dKi,iv:QaNOEPh7kPM9M0+e+itjBAl8bbemY5IxUJcYC3W+zoI=,tag:7/LAx/tj4z89+spg+gwfFw==,type:str]
  password: ENC[AES256_GCM,data:lGKp5QWt,iv:ZKU+gYqjnFjJ7kPpFFaf5xcL2WJl20wfSs6ar/uL2Sw=,tag:RZGnqBAAToy5SYlr17alcw==,type:str]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByS3FCVlhZNC9hWDFqRVc4
        UWtnWHltcW92UGVxM3FWUm05V3orMk1VM2pzCmIxaVFndGF5cjlidjBGaXNCQzJj
        anR3Z0tlb0FXQkljdWQxZnJNSXd5RFEKLS0tIHVvQ1ptYVRFL1JvV0FPUXRuRXhB
        QVdycEFBaENMYUdCcDN6TUVuWXljQ0EKD/FObiHq/BcbX6UAZfSeR4wLft4umuCx
        ODaDRBT3iws9zC7Jsm9oEBPWm+cPIbz6NGdcI+Bsbw4K12Ggei08ag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T21:16:37Z"
  mac: ENC[AES256_GCM,data:jtjsLGl3m/aMaclRhZ9Dc4Trb0QsteP94HcsMa0xRPzHbRfizUPf0h/N/JplN5AGciHAECIf3fcgy/WlixPabOEsSlS0V3BhZVeL6g//6AuKyuJvhMzZ3OlteQIDFCW3m3JG7VfSv4m8e/oyjnTDltgk0HoygrEXnXUAfqNpkko=,iv:YfSDWH3spddw/w+o1iYQ57A21gXYJYTBkctCfIzKetQ=,tag:aHesCbmROXvHM0sg1oe6fA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
