---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kestra
  namespace: kestra
spec:
  interval: 30m
  chart:
    spec:
      chart: kestra
      version: "1.0.36"
      sourceRef:
        kind: HelmRepository
        name: kestra
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    deployments:
      standalone:
        enabled: true
        workerThreads: 0
        dind:
          enabled: true
      webserver:
        enabled: true
      executor:
        enabled: true
      indexer:
        enabled: true
      scheduler:
        enabled: true
      worker:
        enabled: true

    configurations:
      application:
        kestra:
          server:
            basicAuth:
              enabled: false
          repository:
            type: postgres
          queue:
            type: postgres
          tasks:
            tmpDir:
              path: "/tmp/kestra-wd/tmp"

    extraEnv:
      - name: KESTRA_DATASOURCES_POSTGRES_URL
        value: "jdbc:postgresql://kestra-db-rw.kestra.svc.cluster.local:5432/kestra"
      - name: KESTRA_DATASOURCES_POSTGRES_DRIVERCLASSNAME
        value: "org.postgresql.Driver"
      - name: KESTRA_DATASOURCES_POSTGRES_USERNAME
        valueFrom:
          secretKeyRef:
            name: pg-cluster-secret
            key: POSTGRES_USERNAME
      - name: KESTRA_DATASOURCES_POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: pg-cluster-secret
            key: POSTGRES_PASSWORD
      - name: KESTRA_STORAGE_TYPE
        value: "s3"
      - name: KESTRA_STORAGE_S3_BUCKET
        value: "talos-lj-backup"
      - name: KESTRA_STORAGE_S3_REGION
        value: "eu-central-1"
      - name: KESTRA_STORAGE_S3_ENDPOINT
        value: "https://talos-lj-backup.s3.eu-central-1.amazonaws.com"
      - name: KESTRA_STORAGE_S3_ACCESSKEY
        valueFrom:
          secretKeyRef:
            name: s3-creds
            key: ACCESS_KEY_ID
      - name: KESTRA_STORAGE_S3_SECRETKEY
        valueFrom:
          secretKeyRef:
            name: s3-creds
            key: SECRET_ACCESS_KEY

    common:
      securityContext:
        privileged: true
        runAsUser: 0
        runAsGroup: 0
      nodeSelector:
        kubernetes.io/hostname: talos-worker-eu-02

    ingress:
      enabled: true
      className: external
      annotations:
        external-dns.alpha.kubernetes.io/target: kestra.${SECRET_EXTERNAL_DOMAIN}
      hosts:
        - host: kestra.${SECRET_EXTERNAL_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
