apiVersion: v1
kind: Secret
metadata:
  name: s3-creds
  namespace: kestra
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:04BuLJTnAWXyMvajbmGsFWnifd4=,iv:MADzJmwFlYDAKp5mbpTKgE3sCGjh6lAu6tgY0H0/pQs=,tag:XUCoNXKZbbu+ggZuT6aO8w==,type:str]
  SECRET_ACCESS_KEY: ENC[AES256_GCM,data:nw2i0Y3KbdIkPQi2u0k9Gv5CLwIprT+OeLYMseKbS9lYayJeNgqx3A==,iv:PFBePpJA4EvbmEXG+Mk5W8fxqBlHULWaehJO5HhBTXM=,tag:RZp0mRcfw26f23PzYJGWzA==,type:str]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQTFQVmJGUGljdDRTeXFY
        a2hncThOL2xrYTljcVFueGhoZGppSVdnVjFZCm1KRVM0S1o3SFNwcTBTSmo5RU1G
        bE1rd1JGOGJ2cnBBN1Y2SDJhVmUxTlkKLS0tIFVTSVBVVXU4WG04ME0rQkFrTTBj
        WVNGVVJCMllyampuWUZseGNlRWVzZGsKuvmgdTR2Mqwa4lIjIECfjUc7lOrLCwpG
        gTOLMbgOIJnwBMlJICUXYwLilhJhtKpolhhcE6cS5VB0A+9iEFY/zw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T17:59:17Z"
  mac: ENC[AES256_GCM,data:O+kCW5R78J75Q3Rl4vuaMBm/p4LHMHOWnGfWzL+ApMIOQ0Ysg/BbZIAbRWhpLEsC4Cbxn5yGz97Yg7iDdLMHJlGQrPmKui1nPpejCZ9YxfZEHHWKIlfkUTKrW2FeZv1MrKgjRkGsgcQgQzEbYut3gY61/lgWSK+J74cMEsvk4Zc=,iv:18ZGZKV/Rbyl95vu3CQdEauH8DyTSZbgLUtKd7rIGCI=,tag:3CD9DXMXPlqM1i5RCjiCNw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
