---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: linkwarden-db
  namespace: linkwarden
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:16.9
  instances: 1

  bootstrap:
    initdb:
      database: ${POSTGRES_DATABASE}
      owner: ${POSTGRES_USERNAME}
      secret:
        name: pg-cluster-secret

  enableSuperuserAccess: true
  superuserSecret:
    name: pg-cluster-secret

  storage:
    storageClass: longhorn
    size: 1Gi

  externalClusters:
    - name: linkwarden-pg-backup
      barmanObjectStore:
        destinationPath: 's3://talos-lj-backup/linkwarden-pg/'
        s3Credentials:
          accessKeyId:
            name: postgresql-secret
            key: ${ACCESS_KEY_ID}
          secretAccessKey:
            name: postgresql-secret
            key: ${SECRET_ACCESS_KEY}
