---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./storage.yaml
  - ./secret.sops.yaml
  - ./pg-secret.sops.yaml
  - ./cluster-pg.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./ingress.yaml
