
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: linkwarden-db-backup
  namespace: linkwarden
spec:
  schedule: "0 0 * * *"
  suspend: false
  immediate: true
  backupOwnerReference: self
  cluster:
    name: linkwarden-db
