apiVersion: v1
kind: Secret
metadata:
  name: pg-cluster-secret
  namespace: linkwarden
stringData:
  username: ENC[AES256_GCM,data:H7XxEBMhPjVSfWtEvdxOtw==,iv:OMadaRsNhlP8UCSXWq87k+37A1HTO8597R4LfJnXuek=,tag:/cfE0bHLT+w48LlwUBAz+w==,type:str]
  password: ENC[AES256_GCM,data:WuHs7rRWKnQCZqgWMPrifA==,iv:p+1cAKAZYRNErVecg4QeTK5SVyyZL7olRCUEjzcP9D0=,tag:tGD64YFeKFhCKfTm+seSOQ==,type:str]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMU9rRGhkMXFoc0w1d2RK
        UlVSblZKejJ4YTIycG9ETEVVTVJGekQ2SjBFCnhFbEhsTC9sSEUwSWM2eWNJSjdu
        N0t1UVlYMXd5WGdUZUFhNnN5SjhUd00KLS0tIGdPcUtkVjU3WXFoREFCS1NXaHhl
        cWJLdmI4MWIzMzNtQWZwbk9EMkxPTE0Kl6A0U/jjdSurED3QrlvrSpv4uAM8yyuk
        9xUI00tZ4/YWwB6A9nScLQADA73Rtr0aO0Va7RVtfYV2lbAejKfkIA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-09T19:55:13Z"
  mac: ENC[AES256_GCM,data:frBLDYS60A0lPyr1wmMqIJppfubHqA1ctPHwQcL6IJPdKCpmNn5a47dErmuYH+gAWDQ102PPuXQRdIkPX/6v+Ghp2VKXYCRdLrg2Jh6PmyMm39/zCptRySpohug62T7sYWaP6drxNQZOkdACY607aR6YvFv3wLnQj9UaEU2/lcg=,iv:qcxiKQqD7/evPBzorbG1Rnq9n6VQmDfEZumirPY6F6Q=,tag:/yoIlBzWoQh4eu8YkvwR5A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
