apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkwarden
  namespace: linkwarden
spec:
  reclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
