---
originRequest:
  noTLSVerify: true

ingress:
  - hostname: "${SECRET_PROD_DOMAIN}"
    service: https://ingress-nginx-avto-masini-controller.ingress-nginx.svc.cluster.local:443
  - hostname: "*.${SECRET_PROD_DOMAIN}"
    service: https://ingress-nginx-avto-masini-controller.ingress-nginx.svc.cluster.local:443
  - service: http_status:404
