apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
  namespace: avto-masini
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:gk3nDGz2p9ARbp7HmF8uECKWs+3eDv3Er2dFYlwLZtT2PyCx,iv:/KA0QlNWFYrnAMMUWpN+dGW3dd9t+35XS2bg+QH4cU8=,tag:I3dLa4jHeXTA29lmNxMDcg==,type:str]
  credentials.json: ENC[AES256_GCM,data:RmOGx7g5HvdO7qicfp7P6XuNzGFtGm4tyt8AyBWzuJes+9b5kKj6AfvbntFl7Xqxp4JgINbWo5zx36O1D382bSdA/BoGVYpkqhzVDgNH4foCcliNdLny1LDTTSZf921bvH9T0leREcszZBPGRafQfAABSUHaSAWOGkzXydYFUFl8QWe4icABsCaKvF21Z1kBmO1eNbz/AW017qsfXvrvDN03x96aU5CBgMfHJb87/r0=,iv:yZsLTXC+SKisdcPeXhDs5EgjMWuzzx7Si2q6RocVacQ=,tag:xKpGc1zz4AsN6ZB1ec0XDw==,type:str]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCS3dPanhEYkliUjVZVDJP
        MFU2b3ZFZXBKOEJsVmpSMFl3VjZQc3FnUVRzCk9ic2V5c05OMi8veVFMNGVBRGpF
        UnY2RWNlRUdmTW5xRU41VWZ3MmxWSHcKLS0tIFRkaHNqeDZ5Y2hramxaRGpQTVRF
        TGdnWGo0aTVGN3RTcVFGOXlNNmlKZ28KwBHGBJGjDaPPTYcjN0NOd2M+B57YBdy8
        ZA5WR+DYrhsiGu1RVJX+y+vFiNxaAhD10mDEK4JHYTwxzX653GgXYA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-31T08:32:42Z"
  mac: ENC[AES256_GCM,data:1khBCLC0R0Kh2VtSBMbm6oeQurpd+ck97TTXEoJsDF5s2X5HxTZ7t4p4CeDSQJp1hqb1l8yL7iOL/wFyUWm2zGw/VCTLy3Qley+JZxW6FpHbsPg7iomtDn+AIqMIdA8UOxUfvepajNu3YDutjr20jxzXzLrojZdknM4Dx8HhZ9I=,iv:3uY1cfu8FwvStXbn4zADLEggqz8xsCAsFoR5pC86KZY=,tag:vHRYpfdlKhIQ6kp4dOgULw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
