apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-secret
  namespace: cloudflared
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cloudflared-secret
    creationPolicy: Owner
  data:
    - secretKey: TUNNEL_ID
      remoteRef:
        key: secret/data/cloudflared-secret
        property: TUNNEL_ID
    - secretKey: credentials.json
      remoteRef:
        key: secret/data/cloudflared-secret
        property: credentials.json
