---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./dnsendpoint.yaml
  - ./externalsecret.yaml
  - ./release.yaml
configMapGenerator:
  - name: cloudflared-configmap
    namespace: cloudflared
    files:
      - ./configs/config.yaml
generatorOptions:
  disableNameSuffixHash: true
